#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_EnemyPenguin

#include "Basic.hpp"

#include "ABP_EnemyPenguin_classes.hpp"
#include "ABP_EnemyPenguin_parameters.hpp"


SDK_NAMESPACE_START

// Function ABP_EnemyPenguin.ABP_EnemyPenguin_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_EnemyPenguin_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_EnemyPenguin_C", "AnimGraph");

	Params::ABP_EnemyPenguin_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function ABP_EnemyPenguin.ABP_EnemyPenguin_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UABP_EnemyPenguin_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_EnemyPenguin_C", "BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_EnemyPenguin.ABP_EnemyPenguin_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_EnemyPenguin_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_EnemyPenguin_C", "BlueprintUpdateAnimation");

	Params::ABP_EnemyPenguin_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_EnemyPenguin.ABP_EnemyPenguin_C.ExecuteUbergraph_ABP_EnemyPenguin
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_EnemyPenguin_C::ExecuteUbergraph_ABP_EnemyPenguin(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_EnemyPenguin_C", "ExecuteUbergraph_ABP_EnemyPenguin");

	Params::ABP_EnemyPenguin_C_ExecuteUbergraph_ABP_EnemyPenguin Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
