#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_MiniPenguin

#include "Basic.hpp"

#include "ABP_MiniPenguin_classes.hpp"
#include "ABP_MiniPenguin_parameters.hpp"


SDK_NAMESPACE_START

// Function ABP_MiniPenguin.ABP_MiniPenguin_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UABP_MiniPenguin_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_MiniPenguin_C", "AnimGraph");

	Params::ABP_MiniPenguin_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function ABP_MiniPenguin.ABP_MiniPenguin_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UABP_MiniPenguin_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_MiniPenguin_C", "BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_MiniPenguin.ABP_MiniPenguin_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_MiniPenguin_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_MiniPenguin_C", "BlueprintUpdateAnimation");

	Params::ABP_MiniPenguin_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ABP_MiniPenguin.ABP_MiniPenguin_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MiniPenguin_AnimGraphNode_TransitionResult_4E49FAE24595B658CDCDB9AA6E945C84
// (BlueprintEvent)

void UABP_MiniPenguin_C::EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MiniPenguin_AnimGraphNode_TransitionResult_4E49FAE24595B658CDCDB9AA6E945C84()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_MiniPenguin_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_ABP_MiniPenguin_AnimGraphNode_TransitionResult_4E49FAE24595B658CDCDB9AA6E945C84");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ABP_MiniPenguin.ABP_MiniPenguin_C.ExecuteUbergraph_ABP_MiniPenguin
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UABP_MiniPenguin_C::ExecuteUbergraph_ABP_MiniPenguin(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ABP_MiniPenguin_C", "ExecuteUbergraph_ABP_MiniPenguin");

	Params::ABP_MiniPenguin_C_ExecuteUbergraph_ABP_MiniPenguin Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
