#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CraftedObject_GiftBox_2

#include "Basic.hpp"

#include "ENUM_ItemBindType_structs.hpp"
#include "ENUM_ClassType_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "BP_CraftedObject_Base_classes.hpp"
#include "EN_DamageType_structs.hpp"
#include "ENUM_HandType_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CraftedObject_GiftBox_2.BP_CraftedObject_GiftBox_2_C
// 0x0090 (0x03E0 - 0x0350)
class ABP_CraftedObject_GiftBox_2_C final : public ABP_CraftedObject_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_CraftedObject_GiftBox_2_C;       // 0x0350(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      Niagara1;                                          // 0x0358(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      Niagara;                                           // 0x0360(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_368[0x8];                                      // 0x0368(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             DefaultTransform;                                  // 0x0370(0x0060)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         OverrideMass;                                      // 0x03D0(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)

public:
	void Damage(double DamageValue, int32 TeamIndex, EN_DamageType DamageType, const struct FTransform& SourceAgentPoint, bool UnAvoidable, class FName DamageName, class AActor* SourceActor, struct FFinishFilter* Finish);
	void ExecuteUbergraph_BP_CraftedObject_GiftBox_2(int32 EntryPoint);
	void GetItemInfo(ENUM_HandType* HandType, ENUM_ClassType* ClassType, bool* NotPickUp, struct FRotator* HaveRotation, struct FVector* Add_Position, bool* IsBoneAttach, ENUM_ItemBindType* BindType, class FName* BoneName, struct FST_ItemCoreDatas* CoreDatas);
	void IsChangeImage(bool* IsInteract, class FText* OverrideText);
	void OnRep_OverrideMass();
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CraftedObject_GiftBox_2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CraftedObject_GiftBox_2_C")
	}
	static class ABP_CraftedObject_GiftBox_2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CraftedObject_GiftBox_2_C>();
	}
};
// DUMPER7_ASSERTS_ABP_CraftedObject_GiftBox_2_C;

SDK_NAMESPACE_END
