#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CraftedObject_GluePlane

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_CraftedObject_Strage_Base_classes.hpp"
#include "ENUM_ClassType_structs.hpp"
#include "ENUM_ItemBindType_structs.hpp"
#include "ENUM_HandType_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CraftedObject_GluePlane.BP_CraftedObject_GluePlane_C
// 0x0010 (0x0378 - 0x0368)
class ABP_CraftedObject_GluePlane_C final : public ABP_CraftedObject_Strage_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_CraftedObject_GluePlane_C;       // 0x0368(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         OverrideMass;                                      // 0x0370(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          NoGrab;                                            // 0x0374(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_CraftedObject_GluePlane(int32 EntryPoint);
	void GetItemInfo(ENUM_HandType* HandType, ENUM_ClassType* ClassType, bool* NotPickUp, struct FRotator* HaveRotation, struct FVector* Add_Position, bool* IsBoneAttach, ENUM_ItemBindType* BindType, class FName* BoneName, struct FST_ItemCoreDatas* CoreDatas);
	void IsChangeImage(bool* IsInteract, class FText* OverrideText);
	void ReceiveActorBeginOverlap(class AActor* OtherActor);
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CraftedObject_GluePlane_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CraftedObject_GluePlane_C")
	}
	static class ABP_CraftedObject_GluePlane_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CraftedObject_GluePlane_C>();
	}
};
// DUMPER7_ASSERTS_ABP_CraftedObject_GluePlane_C;

SDK_NAMESPACE_END
