#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CraftedObject_GiftBox_2

#include "Basic.hpp"

#include "BP_CraftedObject_GiftBox_2_classes.hpp"
#include "BP_CraftedObject_GiftBox_2_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_CraftedObject_GiftBox_2.BP_CraftedObject_GiftBox_2_C.Damage
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  DamageValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   TeamIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EN_DamageType                           DamageType                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FTransform&                SourceAgentPoint                                       (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    UnAvoidable                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             DamageName                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           SourceActor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FFinishFilter*                   Finish                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CraftedObject_GiftBox_2_C::Damage(double DamageValue, int32 TeamIndex, EN_DamageType DamageType, const struct FTransform& SourceAgentPoint, bool UnAvoidable, class FName DamageName, class AActor* SourceActor, struct FFinishFilter* Finish)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CraftedObject_GiftBox_2_C", "Damage");

	Params::BP_CraftedObject_GiftBox_2_C_Damage Parms{};

	Parms.DamageValue = DamageValue;
	Parms.TeamIndex = TeamIndex;
	Parms.DamageType = DamageType;
	Parms.SourceAgentPoint = std::move(SourceAgentPoint);
	Parms.UnAvoidable = UnAvoidable;
	Parms.DamageName = DamageName;
	Parms.SourceActor = SourceActor;

	UObject::ProcessEvent(Func, &Parms);

	if (Finish != nullptr)
		*Finish = std::move(Parms.Finish);
}


// Function BP_CraftedObject_GiftBox_2.BP_CraftedObject_GiftBox_2_C.ExecuteUbergraph_BP_CraftedObject_GiftBox_2
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_CraftedObject_GiftBox_2_C::ExecuteUbergraph_BP_CraftedObject_GiftBox_2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CraftedObject_GiftBox_2_C", "ExecuteUbergraph_BP_CraftedObject_GiftBox_2");

	Params::BP_CraftedObject_GiftBox_2_C_ExecuteUbergraph_BP_CraftedObject_GiftBox_2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CraftedObject_GiftBox_2.BP_CraftedObject_GiftBox_2_C.GetItemInfo
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// ENUM_HandType*                          HandType                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ENUM_ClassType*                         ClassType                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   NotPickUp                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FRotator*                        HaveRotation                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FVector*                         Add_Position                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   IsBoneAttach                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ENUM_ItemBindType*                      BindType                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName*                            BoneName                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FST_ItemCoreDatas*               CoreDatas                                              (Parm, OutParm, HasGetValueTypeHash)

void ABP_CraftedObject_GiftBox_2_C::GetItemInfo(ENUM_HandType* HandType, ENUM_ClassType* ClassType, bool* NotPickUp, struct FRotator* HaveRotation, struct FVector* Add_Position, bool* IsBoneAttach, ENUM_ItemBindType* BindType, class FName* BoneName, struct FST_ItemCoreDatas* CoreDatas)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CraftedObject_GiftBox_2_C", "GetItemInfo");

	Params::BP_CraftedObject_GiftBox_2_C_GetItemInfo Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (HandType != nullptr)
		*HandType = Parms.HandType;

	if (ClassType != nullptr)
		*ClassType = Parms.ClassType;

	if (NotPickUp != nullptr)
		*NotPickUp = Parms.NotPickUp;

	if (HaveRotation != nullptr)
		*HaveRotation = std::move(Parms.HaveRotation);

	if (Add_Position != nullptr)
		*Add_Position = std::move(Parms.Add_Position);

	if (IsBoneAttach != nullptr)
		*IsBoneAttach = Parms.IsBoneAttach;

	if (BindType != nullptr)
		*BindType = Parms.BindType;

	if (BoneName != nullptr)
		*BoneName = Parms.BoneName;

	if (CoreDatas != nullptr)
		*CoreDatas = std::move(Parms.CoreDatas);
}


// Function BP_CraftedObject_GiftBox_2.BP_CraftedObject_GiftBox_2_C.IsChangeImage
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool*                                   IsInteract                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText*                            OverrideText                                           (Parm, OutParm)

void ABP_CraftedObject_GiftBox_2_C::IsChangeImage(bool* IsInteract, class FText* OverrideText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CraftedObject_GiftBox_2_C", "IsChangeImage");

	Params::BP_CraftedObject_GiftBox_2_C_IsChangeImage Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsInteract != nullptr)
		*IsInteract = Parms.IsInteract;

	if (OverrideText != nullptr)
		*OverrideText = std::move(Parms.OverrideText);
}


// Function BP_CraftedObject_GiftBox_2.BP_CraftedObject_GiftBox_2_C.OnRep_OverrideMass
// (BlueprintCallable, BlueprintEvent)

void ABP_CraftedObject_GiftBox_2_C::OnRep_OverrideMass()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CraftedObject_GiftBox_2_C", "OnRep_OverrideMass");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CraftedObject_GiftBox_2.BP_CraftedObject_GiftBox_2_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_CraftedObject_GiftBox_2_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CraftedObject_GiftBox_2_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
