#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CrouchingCheck

#include "Basic.hpp"

#include "BP_CrouchingCheck_classes.hpp"
#include "BP_CrouchingCheck_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_CrouchingCheck.BP_CrouchingCheck_C.ExecuteUbergraph_BP_CrouchingCheck
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_CrouchingCheck_C::ExecuteUbergraph_BP_CrouchingCheck(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CrouchingCheck_C", "ExecuteUbergraph_BP_CrouchingCheck");

	Params::BP_CrouchingCheck_C_ExecuteUbergraph_BP_CrouchingCheck Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CrouchingCheck.BP_CrouchingCheck_C.K2_OnRegistered
// (Event, Protected, BlueprintEvent)

void UBP_CrouchingCheck_C::K2_OnRegistered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CrouchingCheck_C", "K2_OnRegistered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_CrouchingCheck.BP_CrouchingCheck_C.Trigger
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FSimulationTickParams&     Params_0                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UBP_CrouchingCheck_C::Trigger(const struct FSimulationTickParams& Params_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CrouchingCheck_C", "Trigger");

	Params::BP_CrouchingCheck_C_Trigger Parms{};

	Parms.Params_0 = std::move(Params_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_CrouchingCheck.BP_CrouchingCheck_C.Evaluate
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// const struct FSimulationTickParams&     Params_0                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// struct FTransitionEvalResult            ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor)

struct FTransitionEvalResult UBP_CrouchingCheck_C::Evaluate(const struct FSimulationTickParams& Params_0) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CrouchingCheck_C", "Evaluate");

	Params::BP_CrouchingCheck_C_Evaluate Parms{};

	Parms.Params_0 = std::move(Params_0);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
