#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ClimbingCheck

#include "Basic.hpp"

#include "BP_ClimbingCheck_classes.hpp"
#include "BP_ClimbingCheck_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_ClimbingCheck.BP_ClimbingCheck_C.ExecuteUbergraph_BP_ClimbingCheck
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_ClimbingCheck_C::ExecuteUbergraph_BP_ClimbingCheck(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClimbingCheck_C", "ExecuteUbergraph_BP_ClimbingCheck");

	Params::BP_ClimbingCheck_C_ExecuteUbergraph_BP_ClimbingCheck Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ClimbingCheck.BP_ClimbingCheck_C.Trigger
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FSimulationTickParams&     Params_0                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UBP_ClimbingCheck_C::Trigger(const struct FSimulationTickParams& Params_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClimbingCheck_C", "Trigger");

	Params::BP_ClimbingCheck_C_Trigger Parms{};

	Parms.Params_0 = std::move(Params_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ClimbingCheck.BP_ClimbingCheck_C.Evaluate
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// const struct FSimulationTickParams&     Params_0                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// struct FTransitionEvalResult            ReturnValue                                            (Parm, OutParm, ReturnParm, NoDestructor)

struct FTransitionEvalResult UBP_ClimbingCheck_C::Evaluate(const struct FSimulationTickParams& Params_0) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ClimbingCheck_C", "Evaluate");

	Params::BP_ClimbingCheck_C_Evaluate Parms{};

	Parms.Params_0 = std::move(Params_0);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
