#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FirstPersonPlayerController_Basic

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_FirstPersonPlayerController_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_FirstPersonPlayerController_Basic.BP_FirstPersonPlayerController_Basic_C
// 0x0008 (0x0770 - 0x0768)
class ABP_FirstPersonPlayerController_Basic_C final : public ABP_FirstPersonPlayerController_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_FirstPersonPlayerController_Basic_C; // 0x0768(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void AddMainWidgets();
	void ExecuteUbergraph_BP_FirstPersonPlayerController_Basic(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FirstPersonPlayerController_Basic_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FirstPersonPlayerController_Basic_C")
	}
	static class ABP_FirstPersonPlayerController_Basic_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FirstPersonPlayerController_Basic_C>();
	}
};
// DUMPER7_ASSERTS_ABP_FirstPersonPlayerController_Basic_C;

SDK_NAMESPACE_END
