#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FirstPersonCharacter_LINK

#include "Basic.hpp"

#include "ENUM_ItemBindType_structs.hpp"
#include "ENUM_ClassType_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "BP_FirstPersonCharacter_Main_classes.hpp"
#include "EN_DamageType_structs.hpp"
#include "EN_LINK_PlayerStateValueType_structs.hpp"
#include "ENUM_HandType_structs.hpp"
#include "OnlineSubsystemBlueprints_structs.hpp"
#include "EN_LINK_GamePhase_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_FirstPersonCharacter_LINK.BP_FirstPersonCharacter_LINK_C
// 0x0240 (0x0D70 - 0x0B30)
class ABP_FirstPersonCharacter_LINK_C final : public ABP_FirstPersonCharacter_Main_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_FirstPersonCharacter_LINK_C;     // 0x0B30(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBillboardComponent*                    ItemDropPoint;                                     // 0x0B38(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_LinkCharacterCustomControl_C*      BPC_LinkCharacterCustomControl;                    // 0x0B40(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UWidgetComponent*                       Nameplate;                                         // 0x0B48(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class ULBPC_ComponentDistanceVisualUpdate_C*  LBPC_ComponentDistanceVisualUpdate;                // 0x0B50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_LongInputControl_C*                BPC_LongInputControl_LeftClick;                    // 0x0B58(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCPP_AC_CustomPhysicsForce_2Leg_C*      CPP_AC_CustomPhysicsForce_2Leg;                    // 0x0B60(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAudioCaptureComponent*                 AudioCapture;                                      // 0x0B68(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPhysicsHandleComponent*                PhysicsHandle_R;                                   // 0x0B70(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBPC_LINK_HandControl_C*                BPC_LINK_HandControl_R;                            // 0x0B78(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             HandTransform_R;                                   // 0x0B80(0x0060)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        HandWeight_R;                                      // 0x0BE0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        MaxHandLength;                                     // 0x0BE8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             HandTransform_L;                                   // 0x0BF0(0x0060)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        HandWeight_L;                                      // 0x0C50(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        HandPower;                                         // 0x0C58(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_LINK_MainUI_C*                     LINK_MainUI;                                       // 0x0C60(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class UClass*>                         GiveAbilitys;                                      // 0x0C68(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class ABP_FirstPersonGameMode_Online_LINK_C*  GameMode_LINK;                                     // 0x0C78(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          IsFreeze;                                          // 0x0C80(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C81[0x7];                                      // 0x0C81(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        AttractionDistance;                                // 0x0C88(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_FirstPersonPlayerState_LINK_C*      MyPlayerState_LINK;                                // 0x0C90(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               BodyMaterial;                                      // 0x0C98(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        CurrentVoiceScale;                                 // 0x0CA0(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CA8[0x8];                                      // 0x0CA8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             DeathPointTransform;                               // 0x0CB0(0x0060)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Delta_Seconds;                                     // 0x0D10(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D14[0x4];                                      // 0x0D14(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        OverDamageValue;                                   // 0x0D18(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_GameState_LINK_C*                   As_BP_Game_State_LINK;                             // 0x0D20(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class ABP_MiniPenguin_C*                      MyMiniPenguin;                                     // 0x0D28(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class ABP_TargetPinMain_C*                    TargetPin;                                         // 0x0D30(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class ABP_FirstPersonPlayerController_LINK_C* As_BP_First_Person_Player_Controller_LINK;         // 0x0D38(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	double                                        BeforeBaseWeight;                                  // 0x0D40(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        DefaultHealth;                                     // 0x0D48(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        RevivalHealth;                                     // 0x0D50(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsEmoteSelect;                                     // 0x0D58(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D59[0x7];                                      // 0x0D59(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_EmoteMenu_C*                       EmoteMenuWidget;                                   // 0x0D60(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CurrentEmotePlay;                                  // 0x0D68(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AddMainUI();
	void AimEvent(bool State);
	void AllWidgetHide();
	void AllWidgetShow();
	void BndEvt__BP_FirstPersonCharacter_LINK_AudioCapture_K2Node_ComponentBoundEvent_0_OnSynthEnvelopeValue__DelegateSignature(const float EnvelopeValue);
	void BndEvt__BP_FirstPersonCharacter_LINK_BPC_LINK_HandControl_R_K2Node_ComponentBoundEvent_0_GrabEnd__DelegateSignature(class UPrimitiveComponent* GrabPrimitive);
	void BndEvt__BP_FirstPersonCharacter_LINK_BPC_LinkCharacterCustomControl_K2Node_ComponentBoundEvent_1_OnHeadAccessorieChange__DelegateSignature();
	void BndEvt__BP_FirstPersonCharacter_LINK_BPC_LongInputControl_LeftClick_K2Node_ComponentBoundEvent_1_SinglePush__DelegateSignature();
	void BndEvt__BP_FirstPersonCharacter_LINK_BPC_LongInputControl_LeftClick_K2Node_ComponentBoundEvent_2_LongPushStart__DelegateSignature();
	void BndEvt__BP_FirstPersonCharacter_LINK_BPC_LongInputControl_LeftClick_K2Node_ComponentBoundEvent_3_InputEnd__DelegateSignature(double PushTime);
	void BndEvt__BP_FirstPersonCharacter_LINK_BPC_StaminaGaugeControl_K2Node_ComponentBoundEvent_4_ChangedValue__DelegateSignature(double UpdateValue);
	bool CanDash();
	void CanLook(bool* Rezult);
	void CanSlotChange(bool* Rezult);
	void ChangeCurrentState(class FName StateName);
	void ChangeInteractUITickEvent();
	void ChangeStateValue(EN_LINK_PlayerStateValueType PlayerStateValue, double Value);
	void ChangeViewMode(class FName ModeName, bool Quick);
	void ChangeWeight(double Value);
	void ConnectSignal_Server_();
	void Damage(double DamageValue, int32 TeamIndex, EN_DamageType DamageType, const struct FTransform& SourceAgentPoint, bool UnAvoidable, class FName DamageName, class AActor* SourceActor, struct FFinishFilter* Finish);
	void DamagedAnimation(double DamageValue, bool UnAvoidable);
	void DestroyPin();
	void DropInventoryItem();
	void DropInventoryItem_Server_(int32 SlotIndex, const struct FVector& OverrideDropLocation, bool ForceNoDrop);
	void EmoteStop();
	void ExecuteUbergraph_BP_FirstPersonCharacter_LINK(int32 EntryPoint);
	void ForceGrab(const class AActor* TargetActor);
	void Freeze_Client_();
	void Freeze_Server_();
	void GeneratePin(const struct FTransform& SpawnTransform);
	void GetForceVelocity(class UBPC_LINK_HandControl_C* LINK_HandControl, class USceneComponent* SourcePositionComponent, double power, double DeltaSeconds, struct FVector* Velocity);
	void GetMoveSpeedMultiply(double* MultiplyValue);
	void GetPlayerColor(struct FColor* MainColor);
	bool GetStateValue(class FName TargetName);
	void GiveAxe();
	void Grab(bool State);
	void Grab_Client_(bool State);
	void Heat(double Value);
	void InpActEvt_Ctrl_P_K2Node_InputDebugKeyEvent_3(const struct FKey& Key, const struct FInputActionValue& ActionValue);
	void InpActEvt_Five_K2Node_InputDebugKeyEvent_8(const struct FKey& Key, const struct FInputActionValue& ActionValue);
	void InpActEvt_Four_K2Node_InputKeyEvent_4(const struct FKey& Key);
	void InpActEvt_IA_Emote_K2Node_EnhancedInputActionEvent_1(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Emote_K2Node_EnhancedInputActionEvent_2(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Emote_K2Node_EnhancedInputActionEvent_3(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Move_Default_K2Node_EnhancedInputActionEvent_0(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_Pin_K2Node_EnhancedInputActionEvent_7(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_RotateInput_K2Node_EnhancedInputActionEvent_4(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_RotateInput_K2Node_EnhancedInputActionEvent_5(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_IA_RotateInput_K2Node_EnhancedInputActionEvent_6(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction);
	void InpActEvt_J_K2Node_InputDebugKeyEvent_1(const struct FKey& Key, const struct FInputActionValue& ActionValue);
	void InpActEvt_K_K2Node_InputDebugKeyEvent_0(const struct FKey& Key, const struct FInputActionValue& ActionValue);
	void InpActEvt_L_K2Node_InputDebugKeyEvent_4(const struct FKey& Key, const struct FInputActionValue& ActionValue);
	void InpActEvt_M_K2Node_InputDebugKeyEvent_5(const struct FKey& Key, const struct FInputActionValue& ActionValue);
	void InpActEvt_NumPadFour_K2Node_InputKeyEvent_0(const struct FKey& Key);
	void InpActEvt_NumPadOne_K2Node_InputKeyEvent_3(const struct FKey& Key);
	void InpActEvt_NumPadThree_K2Node_InputKeyEvent_1(const struct FKey& Key);
	void InpActEvt_NumPadTwo_K2Node_InputKeyEvent_2(const struct FKey& Key);
	void InpActEvt_O_K2Node_InputDebugKeyEvent_10(const struct FKey& Key, const struct FInputActionValue& ActionValue);
	void InpActEvt_One_K2Node_InputKeyEvent_7(const struct FKey& Key);
	void InpActEvt_Seven_K2Node_InputDebugKeyEvent_9(const struct FKey& Key, const struct FInputActionValue& ActionValue);
	void InpActEvt_Shift_P_K2Node_InputDebugKeyEvent_2(const struct FKey& Key, const struct FInputActionValue& ActionValue);
	void InpActEvt_Six_K2Node_InputDebugKeyEvent_7(const struct FKey& Key, const struct FInputActionValue& ActionValue);
	void InpActEvt_Three_K2Node_InputKeyEvent_5(const struct FKey& Key);
	void InpActEvt_Two_K2Node_InputKeyEvent_6(const struct FKey& Key);
	void InpActEvt_U_K2Node_InputDebugKeyEvent_11(const struct FKey& Key, const struct FInputActionValue& ActionValue);
	void InpActEvt_V_K2Node_InputDebugKeyEvent_6(const struct FKey& Key, const struct FInputActionValue& ActionValue);
	void Interact_Server_(class AActor* TargetActor, int32 SlotIndex);
	void InventoryStackUpdateSignal();
	void InventoryUpdateSignal();
	void IsBackPackItem(class UObject* Actor, bool* Rezult, struct FST_ItemCoreDatas* CoreDatas);
	bool IsCanClimbing();
	bool IsLive();
	void Kick();
	void NavigateEnd();
	void OnBlendOut_48F7AF4944B2851728DF84BCFBBCFCCA(class FName NotifyName);
	void OnCallFailed_59E542A947E50C239AD252B4B4A3520D(class FName SessionName, bool bWasSuccessful);
	void OnCallFailed_9519D6EA4746536664CE01A6DA07331D(class FName SessionName, bool bWasSuccessful);
	void OnCallFailed_CDC98A21428CD47CDCC078B71D0D8394(class FName SessionName, EOnJoinSessionCompleteResult_ Result);
	void OnCompleted_48F7AF4944B2851728DF84BCFBBCFCCA(class FName NotifyName);
	void OnDestroySessionComplete_59E542A947E50C239AD252B4B4A3520D(class FName SessionName, bool bWasSuccessful);
	void OnDestroySessionComplete_9519D6EA4746536664CE01A6DA07331D(class FName SessionName, bool bWasSuccessful);
	void OnInterrupted_48F7AF4944B2851728DF84BCFBBCFCCA(class FName NotifyName);
	void OnJoinSessionComplete_CDC98A21428CD47CDCC078B71D0D8394(class FName SessionName, EOnJoinSessionCompleteResult_ Result);
	void OnLanded_2(const struct FHitResult& Hit);
	void OnNotifyBegin_48F7AF4944B2851728DF84BCFBBCFCCA(class FName NotifyName);
	void OnNotifyEnd_48F7AF4944B2851728DF84BCFBBCFCCA(class FName NotifyName);
	void OnSessionUserInviteAccepted(bool bWasSuccessful, int32 ControllerId, const struct FUniqueNetIdRepl& UserId, const struct FOnlineSessionSearchResultBP& InviteResult);
	void OverClimbing();
	void PinToTarget_Server_(const struct FVector& Destination, const struct FTransform& SpawnTransform);
	void ReceiveBeginPlay();
	void ReceiveDestroyed();
	void ReceiveTick(float DeltaSeconds);
	void ReleaseLeftItem();
	void ResetAllStates();
	void ResetPowerValue();
	void RezultCheck(const struct FHitResult& Hit, bool* Rezult, class AActor** HitActor, struct FVector* ImpactPoint, class UPrimitiveComponent** HitComponent);
	void SelectIndex(class UClass* EmoteData, int32 Index_0);
	void SetBodyVisibleState(int32 StateIndex);
	void SetCurrentItem(int32 SlotIndex, const struct FCPP_GameItemData& ItemData, const struct FST_ItemCoreDatas& CoreData);
	void SetForce_Server_(class UPrimitiveComponent* Primitive, const struct FVector& NewVel);
	void SetFreeHand();
	void SetHealthValue_LocalClient_(double TargetValue);
	void SetHealthValue_Server_(double TargetValue);
	void SetSlot(int32 TargetSlotValue);
	void SetSpectatingState(bool State);
	void SetUpEndPlayerState();
	void SetVoiceScale_Server_(double CurrentVoiceScale_0);
	void ShortageStamina();
	void ShotEvent(bool State);
	void TargetPositionUpdate(const struct FVector& Position_R, const struct FVector& Position_L);
	void Unzip_Client_();
	void Unzip_Server_(const struct FVector& RespawnPosition);
	void UpdateBackpackWeight(double BackpackWeight);
	void UpdateNameplate(const class FString& playerName);

	void GetIsDeath(bool* IsDeath) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FirstPersonCharacter_LINK_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FirstPersonCharacter_LINK_C")
	}
	static class ABP_FirstPersonCharacter_LINK_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FirstPersonCharacter_LINK_C>();
	}
};
// DUMPER7_ASSERTS_ABP_FirstPersonCharacter_LINK_C;

SDK_NAMESPACE_END
