#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FirstPersonPlayerController_Basic

#include "Basic.hpp"

#include "BP_FirstPersonPlayerController_Basic_classes.hpp"
#include "BP_FirstPersonPlayerController_Basic_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_FirstPersonPlayerController_Basic.BP_FirstPersonPlayerController_Basic_C.AddMainWidgets
// (BlueprintCallable, BlueprintEvent)

void ABP_FirstPersonPlayerController_Basic_C::AddMainWidgets()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FirstPersonPlayerController_Basic_C", "AddMainWidgets");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_FirstPersonPlayerController_Basic.BP_FirstPersonPlayerController_Basic_C.ExecuteUbergraph_BP_FirstPersonPlayerController_Basic
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_FirstPersonPlayerController_Basic_C::ExecuteUbergraph_BP_FirstPersonPlayerController_Basic(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FirstPersonPlayerController_Basic_C", "ExecuteUbergraph_BP_FirstPersonPlayerController_Basic");

	Params::BP_FirstPersonPlayerController_Basic_C_ExecuteUbergraph_BP_FirstPersonPlayerController_Basic Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
