#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FirstPersonPlayerController_Basic

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_FirstPersonPlayerController_Basic.BP_FirstPersonPlayerController_Basic_C.ExecuteUbergraph_BP_FirstPersonPlayerController_Basic
// 0x0004 (0x0004 - 0x0000)
struct BP_FirstPersonPlayerController_Basic_C_ExecuteUbergraph_BP_FirstPersonPlayerController_Basic final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
// DUMPER7_ASSERTS_BP_FirstPersonPlayerController_Basic_C_ExecuteUbergraph_BP_FirstPersonPlayerController_Basic;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
