#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Matchmaker

#include "Basic.hpp"

#include "BP_Matchmaker_classes.hpp"
#include "BP_Matchmaker_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Matchmaker.BP_Matchmaker_C.ExecuteUbergraph_BP_Matchmaker
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Matchmaker_C::ExecuteUbergraph_BP_Matchmaker(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Matchmaker_C", "ExecuteUbergraph_BP_Matchmaker");

	Params::BP_Matchmaker_C_ExecuteUbergraph_BP_Matchmaker Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Matchmaker.BP_Matchmaker_C.OnCancelled
// (Event, Public, BlueprintEvent)

void ABP_Matchmaker_C::OnCancelled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Matchmaker_C", "OnCancelled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Matchmaker.BP_Matchmaker_C.OnError
// (Event, Public, BlueprintEvent)
// Parameters:
// const class FString&                    MatchmakingError                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void ABP_Matchmaker_C::OnError(const class FString& MatchmakingError)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Matchmaker_C", "OnError");

	Params::BP_Matchmaker_C_OnError Parms{};

	Parms.MatchmakingError = std::move(MatchmakingError);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Matchmaker.BP_Matchmaker_C.OnProgress
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FMatchmakerProgressInfo&   ProgressInfo                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABP_Matchmaker_C::OnProgress(const struct FMatchmakerProgressInfo& ProgressInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Matchmaker_C", "OnProgress");

	Params::BP_Matchmaker_C_OnProgress Parms{};

	Parms.ProgressInfo = std::move(ProgressInfo);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Matchmaker.BP_Matchmaker_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Matchmaker_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Matchmaker_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
