#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RedpointPartyMember

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "RedpointEOSFramework_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_RedpointPartyMember.BP_RedpointPartyMember_C
// 0x0018 (0x0308 - 0x02F0)
class ABP_RedpointPartyMember_C final : public ARedpointPartyMember
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Sphere;                                            // 0x02F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0300(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_RedpointPartyMember(int32 EntryPoint);
	void PartyMemberChanged(const struct FRedpointPartyMemberInfo& PartyMember);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RedpointPartyMember_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RedpointPartyMember_C")
	}
	static class ABP_RedpointPartyMember_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_RedpointPartyMember_C>();
	}
};
// DUMPER7_ASSERTS_ABP_RedpointPartyMember_C;

SDK_NAMESPACE_END
