#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RedpointPartyMember

#include "Basic.hpp"

#include "RedpointEOSFramework_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_RedpointPartyMember.BP_RedpointPartyMember_C.ExecuteUbergraph_BP_RedpointPartyMember
// 0x00F8 (0x00F8 - 0x0000)
struct BP_RedpointPartyMember_C_ExecuteUbergraph_BP_RedpointPartyMember final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRedpointPartyMemberInfo               K2Node_Event_PartyMember;                          // 0x0008(0x00F0)(ConstParm)
};
// DUMPER7_ASSERTS_BP_RedpointPartyMember_C_ExecuteUbergraph_BP_RedpointPartyMember;

// Function BP_RedpointPartyMember.BP_RedpointPartyMember_C.PartyMemberChanged
// 0x00F0 (0x00F0 - 0x0000)
struct BP_RedpointPartyMember_C_PartyMemberChanged final
{
public:
	struct FRedpointPartyMemberInfo               PartyMember;                                       // 0x0000(0x00F0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
// DUMPER7_ASSERTS_BP_RedpointPartyMember_C_PartyMemberChanged;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
