#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TeleportPoints

#include "Basic.hpp"

#include "BP_TeleportPoints_classes.hpp"
#include "BP_TeleportPoints_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_TeleportPoints.BP_TeleportPoints_C.GetAllTrasnfroms
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<struct FTransform>*              SpawnTransforms_0                                      (Parm, OutParm)

void ABP_TeleportPoints_C::GetAllTrasnfroms(TArray<struct FTransform>* SpawnTransforms_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeleportPoints_C", "GetAllTrasnfroms");

	Params::BP_TeleportPoints_C_GetAllTrasnfroms Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (SpawnTransforms_0 != nullptr)
		*SpawnTransforms_0 = std::move(Parms.SpawnTransforms_0);
}


// Function BP_TeleportPoints.BP_TeleportPoints_C.SetSpawnPoint
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_TeleportPoints_C::SetSpawnPoint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeleportPoints_C", "SetSpawnPoint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_TeleportPoints.BP_TeleportPoints_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_TeleportPoints_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TeleportPoints_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
