#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_CameraMoveAnimation

#include "Basic.hpp"

#include "BPC_CameraMoveAnimation_classes.hpp"
#include "BPC_CameraMoveAnimation_parameters.hpp"


SDK_NAMESPACE_START

// Function BPC_CameraMoveAnimation.BPC_CameraMoveAnimation_C.AnimationStart
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Front_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Right_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Time                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_CameraMoveAnimation_C::AnimationStart(double Front_0, double Right_0, double Time)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_CameraMoveAnimation_C", "AnimationStart");

	Params::BPC_CameraMoveAnimation_C_AnimationStart Parms{};

	Parms.Front_0 = Front_0;
	Parms.Right_0 = Right_0;
	Parms.Time = Time;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_CameraMoveAnimation.BPC_CameraMoveAnimation_C.ExecuteUbergraph_BPC_CameraMoveAnimation
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_CameraMoveAnimation_C::ExecuteUbergraph_BPC_CameraMoveAnimation(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_CameraMoveAnimation_C", "ExecuteUbergraph_BPC_CameraMoveAnimation");

	Params::BPC_CameraMoveAnimation_C_ExecuteUbergraph_BPC_CameraMoveAnimation Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_CameraMoveAnimation.BPC_CameraMoveAnimation_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBPC_CameraMoveAnimation_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_CameraMoveAnimation_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_CameraMoveAnimation.BPC_CameraMoveAnimation_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_CameraMoveAnimation_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_CameraMoveAnimation_C", "ReceiveTick");

	Params::BPC_CameraMoveAnimation_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
