#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_ItemReplicateController_Parasol

#include "Basic.hpp"

#include "BPC_ItemReplicateController_Parasol_classes.hpp"
#include "BPC_ItemReplicateController_Parasol_parameters.hpp"


SDK_NAMESPACE_START

// Function BPC_ItemReplicateController_Parasol.BPC_ItemReplicateController_Parasol_C.AddForceNoDrop
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void UBPC_ItemReplicateController_Parasol_C::AddForceNoDrop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_ItemReplicateController_Parasol_C", "AddForceNoDrop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_ItemReplicateController_Parasol.BPC_ItemReplicateController_Parasol_C.ExecuteUbergraph_BPC_ItemReplicateController_Parasol
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_ItemReplicateController_Parasol_C::ExecuteUbergraph_BPC_ItemReplicateController_Parasol(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_ItemReplicateController_Parasol_C", "ExecuteUbergraph_BPC_ItemReplicateController_Parasol");

	Params::BPC_ItemReplicateController_Parasol_C_ExecuteUbergraph_BPC_ItemReplicateController_Parasol Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_ItemReplicateController_Parasol.BPC_ItemReplicateController_Parasol_C.ForceClose
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void UBPC_ItemReplicateController_Parasol_C::ForceClose()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_ItemReplicateController_Parasol_C", "ForceClose");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_ItemReplicateController_Parasol.BPC_ItemReplicateController_Parasol_C.OpenParasol(Replicate)
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void UBPC_ItemReplicateController_Parasol_C::OpenParasol_Replicate_()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_ItemReplicateController_Parasol_C", "OpenParasol(Replicate)");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_ItemReplicateController_Parasol.BPC_ItemReplicateController_Parasol_C.OpenParasol(Server)
// (Net, NetServer, BlueprintCallable, BlueprintEvent)

void UBPC_ItemReplicateController_Parasol_C::OpenParasol_Server_()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_ItemReplicateController_Parasol_C", "OpenParasol(Server)");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_ItemReplicateController_Parasol.BPC_ItemReplicateController_Parasol_C.ReceiveEndPlay
// (Event, Public, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_ItemReplicateController_Parasol_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_ItemReplicateController_Parasol_C", "ReceiveEndPlay");

	Params::BPC_ItemReplicateController_Parasol_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_ItemReplicateController_Parasol.BPC_ItemReplicateController_Parasol_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_ItemReplicateController_Parasol_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_ItemReplicateController_Parasol_C", "ReceiveTick");

	Params::BPC_ItemReplicateController_Parasol_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_ItemReplicateController_Parasol.BPC_ItemReplicateController_Parasol_C.UseItem(Local)
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_ItemReplicateController_Parasol_C::UseItem_Local_(bool State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_ItemReplicateController_Parasol_C", "UseItem(Local)");

	Params::BPC_ItemReplicateController_Parasol_C_UseItem_Local_ Parms{};

	Parms.State = State;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_ItemReplicateController_Parasol.BPC_ItemReplicateController_Parasol_C.UseItem(Replicate)
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_ItemReplicateController_Parasol_C::UseItem_Replicate_(bool State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_ItemReplicateController_Parasol_C", "UseItem(Replicate)");

	Params::BPC_ItemReplicateController_Parasol_C_UseItem_Replicate_ Parms{};

	Parms.State = State;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_ItemReplicateController_Parasol.BPC_ItemReplicateController_Parasol_C.UseItem(Server)
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_ItemReplicateController_Parasol_C::UseItem_Server_(bool State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_ItemReplicateController_Parasol_C", "UseItem(Server)");

	Params::BPC_ItemReplicateController_Parasol_C_UseItem_Server_ Parms{};

	Parms.State = State;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
