#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_ItemReplicateController_Parasol

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BPC_ItemReplicateController_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPC_ItemReplicateController_Parasol.BPC_ItemReplicateController_Parasol_C
// 0x0020 (0x0100 - 0x00E0)
class UBPC_ItemReplicateController_Parasol_C final : public UBPC_ItemReplicateController_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BPC_ItemReplicateController_Parasol_C; // 0x00E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UPrimitiveComponent*                    AddForceTarget;                                    // 0x00E8(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        MinDropSpeed;                                      // 0x00F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsUsedItem;                                        // 0x00F8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AddForceNoDrop();
	void ExecuteUbergraph_BPC_ItemReplicateController_Parasol(int32 EntryPoint);
	void ForceClose();
	void OpenParasol_Replicate_();
	void OpenParasol_Server_();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void ReceiveTick(float DeltaSeconds);
	void UseItem_Local_(bool State);
	void UseItem_Replicate_(bool State);
	void UseItem_Server_(bool State);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPC_ItemReplicateController_Parasol_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPC_ItemReplicateController_Parasol_C")
	}
	static class UBPC_ItemReplicateController_Parasol_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_ItemReplicateController_Parasol_C>();
	}
};
// DUMPER7_ASSERTS_UBPC_ItemReplicateController_Parasol_C;

SDK_NAMESPACE_END
