#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_ItemReplicateController_Magnet

#include "Basic.hpp"

#include "BPC_ItemReplicateController_Magnet_classes.hpp"
#include "BPC_ItemReplicateController_Magnet_parameters.hpp"


SDK_NAMESPACE_START

// Function BPC_ItemReplicateController_Magnet.BPC_ItemReplicateController_Magnet_C.ExecuteUbergraph_BPC_ItemReplicateController_Magnet
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_ItemReplicateController_Magnet_C::ExecuteUbergraph_BPC_ItemReplicateController_Magnet(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_ItemReplicateController_Magnet_C", "ExecuteUbergraph_BPC_ItemReplicateController_Magnet");

	Params::BPC_ItemReplicateController_Magnet_C_ExecuteUbergraph_BPC_ItemReplicateController_Magnet Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_ItemReplicateController_Magnet.BPC_ItemReplicateController_Magnet_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_ItemReplicateController_Magnet_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_ItemReplicateController_Magnet_C", "ReceiveTick");

	Params::BPC_ItemReplicateController_Magnet_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_ItemReplicateController_Magnet.BPC_ItemReplicateController_Magnet_C.SetForceTarget
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              AddForceTarget_0                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBPC_ItemReplicateController_Magnet_C::SetForceTarget(class UPrimitiveComponent* AddForceTarget_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_ItemReplicateController_Magnet_C", "SetForceTarget");

	Params::BPC_ItemReplicateController_Magnet_C_SetForceTarget Parms{};

	Parms.AddForceTarget_0 = AddForceTarget_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_ItemReplicateController_Magnet.BPC_ItemReplicateController_Magnet_C.UseItem(Local)
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_ItemReplicateController_Magnet_C::UseItem_Local_(bool State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_ItemReplicateController_Magnet_C", "UseItem(Local)");

	Params::BPC_ItemReplicateController_Magnet_C_UseItem_Local_ Parms{};

	Parms.State = State;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_ItemReplicateController_Magnet.BPC_ItemReplicateController_Magnet_C.UseItem(Replicate)
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_ItemReplicateController_Magnet_C::UseItem_Replicate_(bool State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_ItemReplicateController_Magnet_C", "UseItem(Replicate)");

	Params::BPC_ItemReplicateController_Magnet_C_UseItem_Replicate_ Parms{};

	Parms.State = State;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPC_ItemReplicateController_Magnet.BPC_ItemReplicateController_Magnet_C.UseItem(Server)
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_ItemReplicateController_Magnet_C::UseItem_Server_(bool State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_ItemReplicateController_Magnet_C", "UseItem(Server)");

	Params::BPC_ItemReplicateController_Magnet_C_UseItem_Server_ Parms{};

	Parms.State = State;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
