#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_AIControl

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "EN_StrafingDirection_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPI_AIControl.BPI_AIControl_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_AIControl_C final
{
public:
	void GetAvoidanceRotation(struct FRotator* Rotation);
	void IsAiming(bool* IsAiming_0, int32* SuccessCount);
	void IsAttackNow(bool* State);
	void IsBattleMode(bool* Bool);
	void PlayAvoidanceAnimation();
	void SetStrafing(bool IsStrafing, EN_StrafingDirection Direction);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_AIControl_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_AIControl_C")
	}
	static class IBPI_AIControl_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_AIControl_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
// DUMPER7_ASSERTS_IBPI_AIControl_C;

SDK_NAMESPACE_END
