#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_InPhoto

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "ENUM_ActorType_structs.hpp"
#include "ENUM_CameraMode_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPI_InPhoto.BPI_InPhoto_C
// 0x0000 (0x0000 - 0x0000)
class IBPI_InPhoto_C final
{
public:
	void Delete();
	void GetActorInfo(struct FTransform* DefaultTransform, bool* Not_In_Shot, struct FVector* CentorPosition, bool* IsPenguin, ENUM_ActorType* ActorType, bool* NonInPhoto);
	void GetCentorPosition(TArray<struct FVector>* CentorPosition);
	void GetCopyClass(class UStaticMeshComponent* CentorComponent, class UClass** Class_0, double* Scale, struct FVector* DefaultScale);
	void InAngleOfView(bool InState, double DeltaTime, ENUM_CameraMode CameraMode);
	void Reverse(const struct FTransform& NewPosition, const struct FVector& HitNormal);
	void SetActorInfo(const struct FVector& ToPosition, class USceneComponent* Comp);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPI_InPhoto_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPI_InPhoto_C")
	}
	static class IBPI_InPhoto_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IBPI_InPhoto_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};
// DUMPER7_ASSERTS_IBPI_InPhoto_C;

SDK_NAMESPACE_END
