#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SearchRezult

#include "Basic.hpp"

#include "WBP_SearchRezult_classes.hpp"
#include "WBP_SearchRezult_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_SearchRezult.WBP_SearchRezult_C.BndEvt__WBP_SearchRezult_LongTapButton_OnAnimation_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_SearchRezult_C::BndEvt__WBP_SearchRezult_LongTapButton_OnAnimation_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SearchRezult_C", "BndEvt__WBP_SearchRezult_LongTapButton_OnAnimation_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SearchRezult.WBP_SearchRezult_C.BndEvt__WBP_SearchRezult_UINavButtonBase_127_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_SearchRezult_C::BndEvt__WBP_SearchRezult_UINavButtonBase_127_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SearchRezult_C", "BndEvt__WBP_SearchRezult_UINavButtonBase_127_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SearchRezult.WBP_SearchRezult_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_SearchRezult_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SearchRezult_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SearchRezult.WBP_SearchRezult_C.ExecuteUbergraph_WBP_SearchRezult
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SearchRezult_C::ExecuteUbergraph_WBP_SearchRezult(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SearchRezult_C", "ExecuteUbergraph_WBP_SearchRezult");

	Params::WBP_SearchRezult_C_ExecuteUbergraph_WBP_SearchRezult Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SearchRezult.WBP_SearchRezult_C.OnFailure_AD94403D4AFF5AD99972AF881F91E27A
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ItemId                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const struct FSteamWorkshopItemDetails& Details                                                (BlueprintVisible, BlueprintReadOnly, Parm)
// const class FString&                    ErrorMessage                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_SearchRezult_C::OnFailure_AD94403D4AFF5AD99972AF881F91E27A(const class FString& ItemId, const struct FSteamWorkshopItemDetails& Details, const class FString& ErrorMessage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SearchRezult_C", "OnFailure_AD94403D4AFF5AD99972AF881F91E27A");

	Params::WBP_SearchRezult_C_OnFailure_AD94403D4AFF5AD99972AF881F91E27A Parms{};

	Parms.ItemId = std::move(ItemId);
	Parms.Details = std::move(Details);
	Parms.ErrorMessage = std::move(ErrorMessage);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SearchRezult.WBP_SearchRezult_C.OnSuccess_AD94403D4AFF5AD99972AF881F91E27A
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ItemId                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const struct FSteamWorkshopItemDetails& Details                                                (BlueprintVisible, BlueprintReadOnly, Parm)
// const class FString&                    ErrorMessage                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_SearchRezult_C::OnSuccess_AD94403D4AFF5AD99972AF881F91E27A(const class FString& ItemId, const struct FSteamWorkshopItemDetails& Details, const class FString& ErrorMessage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SearchRezult_C", "OnSuccess_AD94403D4AFF5AD99972AF881F91E27A");

	Params::WBP_SearchRezult_C_OnSuccess_AD94403D4AFF5AD99972AF881F91E27A Parms{};

	Parms.ItemId = std::move(ItemId);
	Parms.Details = std::move(Details);
	Parms.ErrorMessage = std::move(ErrorMessage);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SearchRezult.WBP_SearchRezult_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SearchRezult_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SearchRezult_C", "PreConstruct");

	Params::WBP_SearchRezult_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SearchRezult.WBP_SearchRezult_C.UpdateModState
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<class FString>&            InstalledMod_0                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_SearchRezult_C::UpdateModState(const TArray<class FString>& InstalledMod_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SearchRezult_C", "UpdateModState");

	Params::WBP_SearchRezult_C_UpdateModState Parms{};

	Parms.InstalledMod_0 = std::move(InstalledMod_0);

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
