#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Rule

#include "Basic.hpp"

#include "WBP_Rule_classes.hpp"
#include "WBP_Rule_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_Rule.WBP_Rule_C.BndEvt__WBP_Rule_LongTapButton_OnAnimation_1_K2Node_ComponentBoundEvent_1_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Rule_C::BndEvt__WBP_Rule_LongTapButton_OnAnimation_1_K2Node_ComponentBoundEvent_1_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Rule_C", "BndEvt__WBP_Rule_LongTapButton_OnAnimation_1_K2Node_ComponentBoundEvent_1_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Rule.WBP_Rule_C.BndEvt__WBP_Rule_LongTapButton_OnAnimation_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Rule_C::BndEvt__WBP_Rule_LongTapButton_OnAnimation_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Rule_C", "BndEvt__WBP_Rule_LongTapButton_OnAnimation_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Rule.WBP_Rule_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Rule_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Rule_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Rule.WBP_Rule_C.ExecuteUbergraph_WBP_Rule
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Rule_C::ExecuteUbergraph_WBP_Rule(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Rule_C", "ExecuteUbergraph_WBP_Rule");

	Params::WBP_Rule_C_ExecuteUbergraph_WBP_Rule Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Rule.WBP_Rule_C.OnCallFailed_0646E9BD4A18BBF176FCAEA4D9D7B0B6
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Rule_C::OnCallFailed_0646E9BD4A18BBF176FCAEA4D9D7B0B6(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Rule_C", "OnCallFailed_0646E9BD4A18BBF176FCAEA4D9D7B0B6");

	Params::WBP_Rule_C_OnCallFailed_0646E9BD4A18BBF176FCAEA4D9D7B0B6 Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Rule.WBP_Rule_C.OnReturn
// (Event, Public, BlueprintEvent)

void UWBP_Rule_C::OnReturn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Rule_C", "OnReturn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Rule.WBP_Rule_C.OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA4D9D7B0B6
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Rule_C::OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA4D9D7B0B6(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Rule_C", "OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA4D9D7B0B6");

	Params::WBP_Rule_C_OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA4D9D7B0B6 Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Rule.WBP_Rule_C.OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA4D9D7B0B6
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Rule_C::OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA4D9D7B0B6(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Rule_C", "OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA4D9D7B0B6");

	Params::WBP_Rule_C_OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA4D9D7B0B6 Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Rule.WBP_Rule_C.OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA4D9D7B0B6
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Rule_C::OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA4D9D7B0B6(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Rule_C", "OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA4D9D7B0B6");

	Params::WBP_Rule_C_OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA4D9D7B0B6 Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Rule.WBP_Rule_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Rule_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Rule_C", "PreConstruct");

	Params::WBP_Rule_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Rule.WBP_Rule_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Rule_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Rule_C", "Tick");

	Params::WBP_Rule_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
