#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UserInfo

#include "Basic.hpp"

#include "WBP_UserInfo_classes.hpp"
#include "WBP_UserInfo_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_UserInfo.WBP_UserInfo_C.ExecuteUbergraph_WBP_UserInfo
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UserInfo_C::ExecuteUbergraph_WBP_UserInfo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UserInfo_C", "ExecuteUbergraph_WBP_UserInfo");

	Params::WBP_UserInfo_C_ExecuteUbergraph_WBP_UserInfo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UserInfo.WBP_UserInfo_C.PlayAnimationMessage
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsForward                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UserInfo_C::PlayAnimationMessage(bool IsForward, int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UserInfo_C", "PlayAnimationMessage");

	Params::WBP_UserInfo_C_PlayAnimationMessage Parms{};

	Parms.IsForward = IsForward;
	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UserInfo.WBP_UserInfo_C.SetColor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FLinearColor&              Color                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UserInfo_C::SetColor(const struct FLinearColor& Color, int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UserInfo_C", "SetColor");

	Params::WBP_UserInfo_C_SetColor Parms{};

	Parms.Color = std::move(Color);
	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UserInfo.WBP_UserInfo_C.SetText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UserInfo_C::SetText(const class FText& Text, int32 Index_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_UserInfo_C", "SetText");

	Params::WBP_UserInfo_C_SetText Parms{};

	Parms.Text = std::move(Text);
	Parms.Index_0 = Index_0;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
