#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_VoiceChatUserSettings

#include "Basic.hpp"

#include "WBP_VoiceChatUserSettings_classes.hpp"
#include "WBP_VoiceChatUserSettings_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_VoiceChatUserSettings.WBP_VoiceChatUserSettings_C.BndEvt__WBP_VoiceChatUserSettings_LongTapButton_OnAnimation_K2Node_ComponentBoundEvent_1_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_VoiceChatUserSettings_C::BndEvt__WBP_VoiceChatUserSettings_LongTapButton_OnAnimation_K2Node_ComponentBoundEvent_1_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoiceChatUserSettings_C", "BndEvt__WBP_VoiceChatUserSettings_LongTapButton_OnAnimation_K2Node_ComponentBoundEvent_1_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_VoiceChatUserSettings.WBP_VoiceChatUserSettings_C.BndEvt__WBP_VoiceChatUserSettings_LongTapButton_OnAnimation_Kick_1_K2Node_ComponentBoundEvent_2_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_VoiceChatUserSettings_C::BndEvt__WBP_VoiceChatUserSettings_LongTapButton_OnAnimation_Kick_1_K2Node_ComponentBoundEvent_2_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoiceChatUserSettings_C", "BndEvt__WBP_VoiceChatUserSettings_LongTapButton_OnAnimation_Kick_1_K2Node_ComponentBoundEvent_2_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_VoiceChatUserSettings.WBP_VoiceChatUserSettings_C.BndEvt__WBP_VoiceChatUserSettings_WBP_NavSlider_Penguin_K2Node_ComponentBoundEvent_0_OnValueChangedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_VoiceChatUserSettings_C::BndEvt__WBP_VoiceChatUserSettings_WBP_NavSlider_Penguin_K2Node_ComponentBoundEvent_0_OnValueChangedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoiceChatUserSettings_C", "BndEvt__WBP_VoiceChatUserSettings_WBP_NavSlider_Penguin_K2Node_ComponentBoundEvent_0_OnValueChangedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_VoiceChatUserSettings.WBP_VoiceChatUserSettings_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_VoiceChatUserSettings_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoiceChatUserSettings_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_VoiceChatUserSettings.WBP_VoiceChatUserSettings_C.ConstructSetup
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_FirstPersonPlayerState_Online_C*TargetPlayerState                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_VoiceChatUserSettings_C::ConstructSetup(class ABP_FirstPersonPlayerState_Online_C* TargetPlayerState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoiceChatUserSettings_C", "ConstructSetup");

	Params::WBP_VoiceChatUserSettings_C_ConstructSetup Parms{};

	Parms.TargetPlayerState = TargetPlayerState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_VoiceChatUserSettings.WBP_VoiceChatUserSettings_C.ExecuteUbergraph_WBP_VoiceChatUserSettings
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_VoiceChatUserSettings_C::ExecuteUbergraph_WBP_VoiceChatUserSettings(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoiceChatUserSettings_C", "ExecuteUbergraph_WBP_VoiceChatUserSettings");

	Params::WBP_VoiceChatUserSettings_C_ExecuteUbergraph_WBP_VoiceChatUserSettings Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_VoiceChatUserSettings.WBP_VoiceChatUserSettings_C.OnFinished_1657203944876F75161AA6986A7C9FD9
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FEOSPlayerReportResult&    Result                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_VoiceChatUserSettings_C::OnFinished_1657203944876F75161AA6986A7C9FD9(const struct FEOSPlayerReportResult& Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoiceChatUserSettings_C", "OnFinished_1657203944876F75161AA6986A7C9FD9");

	Params::WBP_VoiceChatUserSettings_C_OnFinished_1657203944876F75161AA6986A7C9FD9 Parms{};

	Parms.Result = std::move(Result);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_VoiceChatUserSettings.WBP_VoiceChatUserSettings_C.PingCheck
// (BlueprintCallable, BlueprintEvent)

void UWBP_VoiceChatUserSettings_C::PingCheck()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoiceChatUserSettings_C", "PingCheck");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_VoiceChatUserSettings.WBP_VoiceChatUserSettings_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_VoiceChatUserSettings_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoiceChatUserSettings_C", "PreConstruct");

	Params::WBP_VoiceChatUserSettings_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_VoiceChatUserSettings.WBP_VoiceChatUserSettings_C.Report
// (BlueprintCallable, BlueprintEvent)

void UWBP_VoiceChatUserSettings_C::Report()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoiceChatUserSettings_C", "Report");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_VoiceChatUserSettings.WBP_VoiceChatUserSettings_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_VoiceChatUserSettings_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoiceChatUserSettings_C", "Tick");

	Params::WBP_VoiceChatUserSettings_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
