#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_TagContent

#include "Basic.hpp"

#include "WBP_TagContent_classes.hpp"
#include "WBP_TagContent_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_TagContent.WBP_TagContent_C.BndEvt__WBP_TagContent_NavButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_TagContent_C::BndEvt__WBP_TagContent_NavButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TagContent_C", "BndEvt__WBP_TagContent_NavButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TagContent.WBP_TagContent_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_TagContent_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TagContent_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TagContent.WBP_TagContent_C.ExecuteUbergraph_WBP_TagContent
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TagContent_C::ExecuteUbergraph_WBP_TagContent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TagContent_C", "ExecuteUbergraph_WBP_TagContent");

	Params::WBP_TagContent_C_ExecuteUbergraph_WBP_TagContent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TagContent.WBP_TagContent_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TagContent_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TagContent_C", "PreConstruct");

	Params::WBP_TagContent_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_TagContent.WBP_TagContent_C.SelectVisualUpdate
// (BlueprintCallable, BlueprintEvent)

void UWBP_TagContent_C::SelectVisualUpdate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TagContent_C", "SelectVisualUpdate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_TagContent.WBP_TagContent_C.SetActiveState
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsSelect_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_TagContent_C::SetActiveState(bool IsSelect_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_TagContent_C", "SetActiveState");

	Params::WBP_TagContent_C_SetActiveState Parms{};

	Parms.IsSelect_0 = IsSelect_0;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
