#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_VoiceChatLists

#include "Basic.hpp"

#include "WBP_VoiceChatLists_classes.hpp"
#include "WBP_VoiceChatLists_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_VoiceChatLists.WBP_VoiceChatLists_C.ExecuteUbergraph_WBP_VoiceChatLists
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_VoiceChatLists_C::ExecuteUbergraph_WBP_VoiceChatLists(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoiceChatLists_C", "ExecuteUbergraph_WBP_VoiceChatLists");

	Params::WBP_VoiceChatLists_C_ExecuteUbergraph_WBP_VoiceChatLists Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_VoiceChatLists.WBP_VoiceChatLists_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_VoiceChatLists_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoiceChatLists_C", "PreConstruct");

	Params::WBP_VoiceChatLists_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_VoiceChatLists.WBP_VoiceChatLists_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_VoiceChatLists_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoiceChatLists_C", "Tick");

	Params::WBP_VoiceChatLists_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_VoiceChatLists.WBP_VoiceChatLists_C.VoiceStateUpdate
// (BlueprintCallable, BlueprintEvent)

void UWBP_VoiceChatLists_C::VoiceStateUpdate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_VoiceChatLists_C", "VoiceStateUpdate");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
