#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LS_FallDownPlayerSub1

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "LevelSequence_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass LS_FallDownPlayerSub1.LS_FallDownPlayerSub1_DirectorBP_C
// 0x0008 (0x0050 - 0x0048)
class ULS_FallDownPlayerSub1_DirectorBP_C final : public ULevelSequenceDirector
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0048(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	struct FMovieSceneDynamicBindingResolveResult BP_FirstPersonCharacter_DynamicBinding();
	struct FMovieSceneDynamicBindingResolveResult BP_FirstPersonCharacter_DynamicBinding_0(int32 PlayerControllerIndex);
	void BP_FirstPersonCharacter_Event(class ABP_FirstPersonCharacter_Main_C* BP_FirstPersonCharacter);
	struct FMovieSceneDynamicBindingResolveResult CameraActor_DynamicBinding();
	void ExecuteUbergraph_LS_FallDownPlayerSub1_DirectorBP(int32 EntryPoint);
	struct FMovieSceneDynamicBindingResolveResult HeadPosition_DynamicBinding();
	struct FMovieSceneDynamicBindingResolveResult LeftPos_DynamicBinding();
	struct FMovieSceneDynamicBindingResolveResult RightPos_DynamicBinding();
	struct FMovieSceneDynamicBindingResolveResult RightPos_DynamicBinding_0();
	struct FMovieSceneDynamicBindingResolveResult SequenceEvent__ENTRYPOINTLS_FallDownPlayerSub1_DirectorBP();
	struct FMovieSceneDynamicBindingResolveResult SequenceEvent__ENTRYPOINTLS_FallDownPlayerSub1_DirectorBP_0();
	struct FMovieSceneDynamicBindingResolveResult SequenceEvent__ENTRYPOINTLS_FallDownPlayerSub1_DirectorBP_1();
	void SequenceEvent__ENTRYPOINTLS_FallDownPlayerSub1_DirectorBP_2(class ABP_FirstPersonCharacter_Main_C* BP_FirstPersonCharacter);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LS_FallDownPlayerSub1_DirectorBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LS_FallDownPlayerSub1_DirectorBP_C")
	}
	static class ULS_FallDownPlayerSub1_DirectorBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULS_FallDownPlayerSub1_DirectorBP_C>();
	}
};
// DUMPER7_ASSERTS_ULS_FallDownPlayerSub1_DirectorBP_C;

SDK_NAMESPACE_END
