#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LS_TouchMiniPenguin

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "LevelSequence_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass LS_TouchMiniPenguin.LS_TouchMiniPenguin_DirectorBP_C
// 0x0008 (0x0050 - 0x0048)
class ULS_TouchMiniPenguin_DirectorBP_C final : public ULevelSequenceDirector
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0048(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void BP_AI_Base_Event(class ABP_AI_Base_C* BP_AI_Base);
	void BP_FirstPersonCharacter_Event(class ABP_FirstPersonCharacter_Main_C* BP_FirstPersonCharacter);
	void ExecuteUbergraph_LS_TouchMiniPenguin_DirectorBP(int32 EntryPoint);
	struct FMovieSceneDynamicBindingResolveResult HeadPosition_DynamicBinding();
	struct FMovieSceneDynamicBindingResolveResult LeftItemPositon_DynamicBinding();
	struct FMovieSceneDynamicBindingResolveResult RightItemPositon_DynamicBinding();
	void SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP(class ABP_AI_Base_C* BP_AI_Base);
	void SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP_0(class ABP_FirstPersonCharacter_Main_C* BP_FirstPersonCharacter);
	struct FMovieSceneDynamicBindingResolveResult SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP_1();
	struct FMovieSceneDynamicBindingResolveResult SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP_2();
	struct FMovieSceneDynamicBindingResolveResult SequenceEvent__ENTRYPOINTLS_TouchMiniPenguin_DirectorBP_3();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LS_TouchMiniPenguin_DirectorBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LS_TouchMiniPenguin_DirectorBP_C")
	}
	static class ULS_TouchMiniPenguin_DirectorBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULS_TouchMiniPenguin_DirectorBP_C>();
	}
};
// DUMPER7_ASSERTS_ULS_TouchMiniPenguin_DirectorBP_C;

SDK_NAMESPACE_END
