#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MyGameMode

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass MyGameMode.MyGameMode_C
// 0x0008 (0x0348 - 0x0340)
class AMyGameMode_C final : public AGameModeBase
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MyGameMode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MyGameMode_C")
	}
	static class AMyGameMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMyGameMode_C>();
	}
};
// DUMPER7_ASSERTS_AMyGameMode_C;

SDK_NAMESPACE_END
