#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ST_SearchTagInfo

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct ST_SearchTagInfo.ST_SearchTagInfo
// 0x0020 (0x0020 - 0x0000)
struct FST_SearchTagInfo final
{
public:
	class FText                                   TagText_2_A83C6F15414BEDAE3959ED9DB51BB213;        // 0x0000(0x0010)(Edit, BlueprintVisible)
	struct FLinearColor                           BGColor_5_6E4475DE4D29D984A503279AC85D03C5;        // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
// DUMPER7_ASSERTS_FST_SearchTagInfo;

SDK_NAMESPACE_END
