#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_OptionBox_VoiceInputOrOutputDevice

#include "Basic.hpp"

#include "WBP_OptionBox_VoiceInputOrOutputDevice_classes.hpp"
#include "WBP_OptionBox_VoiceInputOrOutputDevice_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_OptionBox_VoiceInputOrOutputDevice.WBP_OptionBox_VoiceInputOrOutputDevice_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_OptionBox_VoiceInputOrOutputDevice_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionBox_VoiceInputOrOutputDevice_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OptionBox_VoiceInputOrOutputDevice.WBP_OptionBox_VoiceInputOrOutputDevice_C.ExecuteUbergraph_WBP_OptionBox_VoiceInputOrOutputDevice
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OptionBox_VoiceInputOrOutputDevice_C::ExecuteUbergraph_WBP_OptionBox_VoiceInputOrOutputDevice(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionBox_VoiceInputOrOutputDevice_C", "ExecuteUbergraph_WBP_OptionBox_VoiceInputOrOutputDevice");

	Params::WBP_OptionBox_VoiceInputOrOutputDevice_C_ExecuteUbergraph_WBP_OptionBox_VoiceInputOrOutputDevice Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OptionBox_VoiceInputOrOutputDevice.WBP_OptionBox_VoiceInputOrOutputDevice_C.OnValueChangeEvent
// (BlueprintCallable, BlueprintEvent)

void UWBP_OptionBox_VoiceInputOrOutputDevice_C::OnValueChangeEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionBox_VoiceInputOrOutputDevice_C", "OnValueChangeEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_OptionBox_VoiceInputOrOutputDevice.WBP_OptionBox_VoiceInputOrOutputDevice_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OptionBox_VoiceInputOrOutputDevice_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionBox_VoiceInputOrOutputDevice_C", "PreConstruct");

	Params::WBP_OptionBox_VoiceInputOrOutputDevice_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_OptionBox_VoiceInputOrOutputDevice.WBP_OptionBox_VoiceInputOrOutputDevice_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_OptionBox_VoiceInputOrOutputDevice_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_OptionBox_VoiceInputOrOutputDevice_C", "Tick");

	Params::WBP_OptionBox_VoiceInputOrOutputDevice_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
