#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PrivateOrPublic

#include "Basic.hpp"

#include "WBP_PrivateOrPublic_classes.hpp"
#include "WBP_PrivateOrPublic_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_PrivateOrPublic.WBP_PrivateOrPublic_C.BndEvt__WBP_PrivateOrPublic_LongTapButton_SearchFriendServer_K2Node_ComponentBoundEvent_2_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_PrivateOrPublic_C::BndEvt__WBP_PrivateOrPublic_LongTapButton_SearchFriendServer_K2Node_ComponentBoundEvent_2_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PrivateOrPublic_C", "BndEvt__WBP_PrivateOrPublic_LongTapButton_SearchFriendServer_K2Node_ComponentBoundEvent_2_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PrivateOrPublic.WBP_PrivateOrPublic_C.BndEvt__WBP_PrivateOrPublic_LongTapButton_SearchPrivateServer_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_PrivateOrPublic_C::BndEvt__WBP_PrivateOrPublic_LongTapButton_SearchPrivateServer_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PrivateOrPublic_C", "BndEvt__WBP_PrivateOrPublic_LongTapButton_SearchPrivateServer_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PrivateOrPublic.WBP_PrivateOrPublic_C.BndEvt__WBP_PrivateOrPublic_LongTapButton_SearchPublicServer_K2Node_ComponentBoundEvent_1_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_PrivateOrPublic_C::BndEvt__WBP_PrivateOrPublic_LongTapButton_SearchPublicServer_K2Node_ComponentBoundEvent_1_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PrivateOrPublic_C", "BndEvt__WBP_PrivateOrPublic_LongTapButton_SearchPublicServer_K2Node_ComponentBoundEvent_1_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PrivateOrPublic.WBP_PrivateOrPublic_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_PrivateOrPublic_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PrivateOrPublic_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PrivateOrPublic.WBP_PrivateOrPublic_C.ExecuteUbergraph_WBP_PrivateOrPublic
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PrivateOrPublic_C::ExecuteUbergraph_WBP_PrivateOrPublic(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PrivateOrPublic_C", "ExecuteUbergraph_WBP_PrivateOrPublic");

	Params::WBP_PrivateOrPublic_C_ExecuteUbergraph_WBP_PrivateOrPublic Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
