#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CloudSaveLoad

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UINavigation_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_CloudSaveLoad.WBP_CloudSaveLoad_C
// 0x0048 (0x0538 - 0x04F0)
class UWBP_CloudSaveLoad_C final : public UUINavWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             TextBlock_161;                                     // 0x04F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock;                                         // 0x0500(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_1;                                           // 0x0508(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_0;                                           // 0x0510(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   DefaultText;                                       // 0x0518(0x0010)(Edit, BlueprintVisible)
	class FString                                 AppentText;                                        // 0x0528(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void DotPlus();
	void ExecuteUbergraph_WBP_CloudSaveLoad(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_CloudSaveLoad_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_CloudSaveLoad_C")
	}
	static class UWBP_CloudSaveLoad_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_CloudSaveLoad_C>();
	}
};
// DUMPER7_ASSERTS_UWBP_CloudSaveLoad_C;

SDK_NAMESPACE_END
