#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CloudSaveLoad

#include "Basic.hpp"

#include "WBP_CloudSaveLoad_classes.hpp"
#include "WBP_CloudSaveLoad_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_CloudSaveLoad.WBP_CloudSaveLoad_C.DotPlus
// (BlueprintCallable, BlueprintEvent)

void UWBP_CloudSaveLoad_C::DotPlus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CloudSaveLoad_C", "DotPlus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CloudSaveLoad.WBP_CloudSaveLoad_C.ExecuteUbergraph_WBP_CloudSaveLoad
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CloudSaveLoad_C::ExecuteUbergraph_WBP_CloudSaveLoad(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CloudSaveLoad_C", "ExecuteUbergraph_WBP_CloudSaveLoad");

	Params::WBP_CloudSaveLoad_C_ExecuteUbergraph_WBP_CloudSaveLoad Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CloudSaveLoad.WBP_CloudSaveLoad_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CloudSaveLoad_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CloudSaveLoad_C", "PreConstruct");

	Params::WBP_CloudSaveLoad_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
