#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_cLeonSessionSettings_SearchPrivateSession

#include "Basic.hpp"

#include "WBP_cLeonSessionSettings_SearchPrivateSession_classes.hpp"
#include "WBP_cLeonSessionSettings_SearchPrivateSession_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.BndEvt__WBP_cLeonSessionSettings_LongTapButton_SearchPublicSession_K2Node_ComponentBoundEvent_5_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::BndEvt__WBP_cLeonSessionSettings_LongTapButton_SearchPublicSession_K2Node_ComponentBoundEvent_5_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "BndEvt__WBP_cLeonSessionSettings_LongTapButton_SearchPublicSession_K2Node_ComponentBoundEvent_5_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.BndEvt__WBP_cLeonSessionSettings_UpdateModState_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::BndEvt__WBP_cLeonSessionSettings_UpdateModState_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "BndEvt__WBP_cLeonSessionSettings_UpdateModState_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.BndEvt__WBP_LinkSessionSettings_LongTapButton_CreateSession_K2Node_ComponentBoundEvent_1_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::BndEvt__WBP_LinkSessionSettings_LongTapButton_CreateSession_K2Node_ComponentBoundEvent_1_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "BndEvt__WBP_LinkSessionSettings_LongTapButton_CreateSession_K2Node_ComponentBoundEvent_1_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.BndEvt__WBP_LinkSessionSettings_LongTapButton_JoinSession_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::BndEvt__WBP_LinkSessionSettings_LongTapButton_JoinSession_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "BndEvt__WBP_LinkSessionSettings_LongTapButton_JoinSession_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_Password_K2Node_ComponentBoundEvent_4_OnTextCommitted__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// ETextCommit                             CommitMethod                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_Password_K2Node_ComponentBoundEvent_4_OnTextCommitted__DelegateSignature(const class FText& Text, ETextCommit CommitMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_Password_K2Node_ComponentBoundEvent_4_OnTextCommitted__DelegateSignature");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_Password_K2Node_ComponentBoundEvent_4_OnTextCommitted__DelegateSignature Parms{};

	Parms.Text = std::move(Text);
	Parms.CommitMethod = CommitMethod;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_SessionName_K2Node_ComponentBoundEvent_3_OnTextCommitted__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// ETextCommit                             CommitMethod                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_SessionName_K2Node_ComponentBoundEvent_3_OnTextCommitted__DelegateSignature(const class FText& Text, ETextCommit CommitMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_SessionName_K2Node_ComponentBoundEvent_3_OnTextCommitted__DelegateSignature");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_SessionName_K2Node_ComponentBoundEvent_3_OnTextCommitted__DelegateSignature Parms{};

	Parms.Text = std::move(Text);
	Parms.CommitMethod = CommitMethod;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_UserName_K2Node_ComponentBoundEvent_2_OnTextCommitted__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// ETextCommit                             CommitMethod                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_UserName_K2Node_ComponentBoundEvent_2_OnTextCommitted__DelegateSignature(const class FText& Text, ETextCommit CommitMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_UserName_K2Node_ComponentBoundEvent_2_OnTextCommitted__DelegateSignature");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_UserName_K2Node_ComponentBoundEvent_2_OnTextCommitted__DelegateSignature Parms{};

	Parms.Text = std::move(Text);
	Parms.CommitMethod = CommitMethod;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.ExecuteUbergraph_WBP_cLeonSessionSettings_SearchPrivateSession
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::ExecuteUbergraph_WBP_cLeonSessionSettings_SearchPrivateSession(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "ExecuteUbergraph_WBP_cLeonSessionSettings_SearchPrivateSession");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_ExecuteUbergraph_WBP_cLeonSessionSettings_SearchPrivateSession Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.Finish
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Rezult                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::Finish(bool Rezult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "Finish");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_Finish Parms{};

	Parms.Rezult = Rezult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.GetRegionName
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FString*                          ReturnString                                           (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::GetRegionName(class FString* ReturnString)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "GetRegionName");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_GetRegionName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ReturnString != nullptr)
		*ReturnString = std::move(Parms.ReturnString);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.GetSearchOption
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FST_SessionOptionString>* Options                                                (Parm, OutParm)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::GetSearchOption(TArray<struct FST_SessionOptionString>* Options)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "GetSearchOption");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_GetSearchOption Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Options != nullptr)
		*Options = std::move(Parms.Options);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.GetSearchParamaters
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TMap<class FName, struct FSessionSearchParamBP>*Map                                                    (Parm, OutParm)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::GetSearchParamaters(TMap<class FName, struct FSessionSearchParamBP>* Map)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "GetSearchParamaters");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_GetSearchParamaters Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Map != nullptr)
		*Map = std::move(Parms.Map);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.GetSessionSettings
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FOnlineSessionSettingsBP*        OnlineSessionSettingsBP                                (Parm, OutParm)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::GetSessionSettings(struct FOnlineSessionSettingsBP* OnlineSessionSettingsBP)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "GetSessionSettings");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_GetSessionSettings Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OnlineSessionSettingsBP != nullptr)
		*OnlineSessionSettingsBP = std::move(Parms.OnlineSessionSettingsBP);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.GetTagNames
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class FName>*                    ReturnTagNames                                         (Parm, OutParm)
// class FString*                          ReturnString                                           (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::GetTagNames(TArray<class FName>* ReturnTagNames, class FString* ReturnString)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "GetTagNames");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_GetTagNames Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ReturnTagNames != nullptr)
		*ReturnTagNames = std::move(Parms.ReturnTagNames);

	if (ReturnString != nullptr)
		*ReturnString = std::move(Parms.ReturnString);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.JoinSession
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FOnlineSessionSearchResultBP&SearchRezult                                           (BlueprintVisible, BlueprintReadOnly, Parm)
// class UWBP_SearchRezult_C*              SelfObject                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::JoinSession(const struct FOnlineSessionSearchResultBP& SearchRezult, class UWBP_SearchRezult_C* SelfObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "JoinSession");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_JoinSession Parms{};

	Parms.SearchRezult = std::move(SearchRezult);
	Parms.SelfObject = SelfObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.OnActivateEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_TagContent_C*                MyWidget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::OnActivateEvent(class UWBP_TagContent_C* MyWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "OnActivateEvent");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_OnActivateEvent Parms{};

	Parms.MyWidget = MyWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.OnCallFailed_0369059F404B654993F662BD6A2CB9A1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             SessionName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::OnCallFailed_0369059F404B654993F662BD6A2CB9A1(class FName SessionName, bool bWasSuccessful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "OnCallFailed_0369059F404B654993F662BD6A2CB9A1");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_OnCallFailed_0369059F404B654993F662BD6A2CB9A1 Parms{};

	Parms.SessionName = SessionName;
	Parms.bWasSuccessful = bWasSuccessful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.OnCallFailed_0646E9BD4A18BBF176FCAEA4ACF8D20A
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::OnCallFailed_0646E9BD4A18BBF176FCAEA4ACF8D20A(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "OnCallFailed_0646E9BD4A18BBF176FCAEA4ACF8D20A");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_OnCallFailed_0646E9BD4A18BBF176FCAEA4ACF8D20A Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.OnCallFailed_0646E9BD4A18BBF176FCAEA4BADE6A3C
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::OnCallFailed_0646E9BD4A18BBF176FCAEA4BADE6A3C(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "OnCallFailed_0646E9BD4A18BBF176FCAEA4BADE6A3C");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_OnCallFailed_0646E9BD4A18BBF176FCAEA4BADE6A3C Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.OnCallFailed_09BA91194B2AE475EC58A699DAA3254A
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             SessionName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EOnJoinSessionCompleteResult_           Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::OnCallFailed_09BA91194B2AE475EC58A699DAA3254A(class FName SessionName, EOnJoinSessionCompleteResult_ Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "OnCallFailed_09BA91194B2AE475EC58A699DAA3254A");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_OnCallFailed_09BA91194B2AE475EC58A699DAA3254A Parms{};

	Parms.SessionName = SessionName;
	Parms.Result = Result;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.OnCallFailed_1C7907C84B9BCBDA7B50F2A06B0BF233
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::OnCallFailed_1C7907C84B9BCBDA7B50F2A06B0BF233(bool bWasSuccessful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "OnCallFailed_1C7907C84B9BCBDA7B50F2A06B0BF233");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_OnCallFailed_1C7907C84B9BCBDA7B50F2A06B0BF233 Parms{};

	Parms.bWasSuccessful = bWasSuccessful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.OnCallFailed_1C7907C84B9BCBDA7B50F2A0B9ECD3F4
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::OnCallFailed_1C7907C84B9BCBDA7B50F2A0B9ECD3F4(bool bWasSuccessful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "OnCallFailed_1C7907C84B9BCBDA7B50F2A0B9ECD3F4");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_OnCallFailed_1C7907C84B9BCBDA7B50F2A0B9ECD3F4 Parms{};

	Parms.bWasSuccessful = bWasSuccessful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.OnCreateSessionComplete_0369059F404B654993F662BD6A2CB9A1
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             SessionName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::OnCreateSessionComplete_0369059F404B654993F662BD6A2CB9A1(class FName SessionName, bool bWasSuccessful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "OnCreateSessionComplete_0369059F404B654993F662BD6A2CB9A1");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_OnCreateSessionComplete_0369059F404B654993F662BD6A2CB9A1 Parms{};

	Parms.SessionName = SessionName;
	Parms.bWasSuccessful = bWasSuccessful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.OnFindSessionsComplete_1C7907C84B9BCBDA7B50F2A06B0BF233
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::OnFindSessionsComplete_1C7907C84B9BCBDA7B50F2A06B0BF233(bool bWasSuccessful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "OnFindSessionsComplete_1C7907C84B9BCBDA7B50F2A06B0BF233");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_OnFindSessionsComplete_1C7907C84B9BCBDA7B50F2A06B0BF233 Parms{};

	Parms.bWasSuccessful = bWasSuccessful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.OnFindSessionsComplete_1C7907C84B9BCBDA7B50F2A0B9ECD3F4
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::OnFindSessionsComplete_1C7907C84B9BCBDA7B50F2A0B9ECD3F4(bool bWasSuccessful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "OnFindSessionsComplete_1C7907C84B9BCBDA7B50F2A0B9ECD3F4");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_OnFindSessionsComplete_1C7907C84B9BCBDA7B50F2A0B9ECD3F4 Parms{};

	Parms.bWasSuccessful = bWasSuccessful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.OnFocusLost
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::OnFocusLost(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "OnFocusLost");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_OnFocusLost Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.OnJoinSessionComplete_09BA91194B2AE475EC58A699DAA3254A
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             SessionName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EOnJoinSessionCompleteResult_           Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::OnJoinSessionComplete_09BA91194B2AE475EC58A699DAA3254A(class FName SessionName, EOnJoinSessionCompleteResult_ Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "OnJoinSessionComplete_09BA91194B2AE475EC58A699DAA3254A");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_OnJoinSessionComplete_09BA91194B2AE475EC58A699DAA3254A Parms{};

	Parms.SessionName = SessionName;
	Parms.Result = Result;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.OnReturn
// (Event, Public, BlueprintEvent)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::OnReturn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "OnReturn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA4ACF8D20A
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA4ACF8D20A(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA4ACF8D20A");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA4ACF8D20A Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA4BADE6A3C
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA4BADE6A3C(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA4BADE6A3C");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA4BADE6A3C Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA4ACF8D20A
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA4ACF8D20A(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA4ACF8D20A");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA4ACF8D20A Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA4BADE6A3C
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA4BADE6A3C(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA4BADE6A3C");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA4BADE6A3C Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA4ACF8D20A
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA4ACF8D20A(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA4ACF8D20A");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA4ACF8D20A Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA4BADE6A3C
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA4BADE6A3C(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA4BADE6A3C");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA4BADE6A3C Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "PreConstruct");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.SelectMod
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ModId                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class UWBP_CustomMapParts_C*            SelfWidget                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::SelectMod(const class FString& ModId, class UWBP_CustomMapParts_C* SelfWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "SelectMod");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_SelectMod Parms{};

	Parms.ModId = std::move(ModId);
	Parms.SelfWidget = SelfWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "Tick");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.UpdateSearch
// (BlueprintCallable, BlueprintEvent)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::UpdateSearch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "UpdateSearch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_cLeonSessionSettings_SearchPrivateSession.WBP_cLeonSessionSettings_SearchPrivateSession_C.WarningControl
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<int32>&                          WarningIndex                                           (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_cLeonSessionSettings_SearchPrivateSession_C::WarningControl(TArray<int32>& WarningIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchPrivateSession_C", "WarningControl");

	Params::WBP_cLeonSessionSettings_SearchPrivateSession_C_WarningControl Parms{};

	Parms.WarningIndex = std::move(WarningIndex);

	UObject::ProcessEvent(Func, &Parms);

	WarningIndex = std::move(Parms.WarningIndex);
}


SDK_NAMESPACE_END
