#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ReciveInvite

#include "Basic.hpp"

#include "WBP_ReciveInvite_classes.hpp"
#include "WBP_ReciveInvite_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_ReciveInvite.WBP_ReciveInvite_C.BndEvt__WBP_ReciveInvite_LongTapButton_OnAnimation_Ignore_K2Node_ComponentBoundEvent_1_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_ReciveInvite_C::BndEvt__WBP_ReciveInvite_LongTapButton_OnAnimation_Ignore_K2Node_ComponentBoundEvent_1_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReciveInvite_C", "BndEvt__WBP_ReciveInvite_LongTapButton_OnAnimation_Ignore_K2Node_ComponentBoundEvent_1_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ReciveInvite.WBP_ReciveInvite_C.BndEvt__WBP_ReciveInvite_LongTapButton_OnAnimation_Join_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_ReciveInvite_C::BndEvt__WBP_ReciveInvite_LongTapButton_OnAnimation_Join_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReciveInvite_C", "BndEvt__WBP_ReciveInvite_LongTapButton_OnAnimation_Join_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ReciveInvite.WBP_ReciveInvite_C.ExecuteUbergraph_WBP_ReciveInvite
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ReciveInvite_C::ExecuteUbergraph_WBP_ReciveInvite(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReciveInvite_C", "ExecuteUbergraph_WBP_ReciveInvite");

	Params::WBP_ReciveInvite_C_ExecuteUbergraph_WBP_ReciveInvite Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ReciveInvite.WBP_ReciveInvite_C.OnCallFailed_77D215C44210C770FBA086B82A2056BC
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             SessionName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EOnJoinSessionCompleteResult_           Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ReciveInvite_C::OnCallFailed_77D215C44210C770FBA086B82A2056BC(class FName SessionName, EOnJoinSessionCompleteResult_ Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReciveInvite_C", "OnCallFailed_77D215C44210C770FBA086B82A2056BC");

	Params::WBP_ReciveInvite_C_OnCallFailed_77D215C44210C770FBA086B82A2056BC Parms{};

	Parms.SessionName = SessionName;
	Parms.Result = Result;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ReciveInvite.WBP_ReciveInvite_C.OnJoinSessionComplete_77D215C44210C770FBA086B82A2056BC
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             SessionName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EOnJoinSessionCompleteResult_           Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ReciveInvite_C::OnJoinSessionComplete_77D215C44210C770FBA086B82A2056BC(class FName SessionName, EOnJoinSessionCompleteResult_ Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReciveInvite_C", "OnJoinSessionComplete_77D215C44210C770FBA086B82A2056BC");

	Params::WBP_ReciveInvite_C_OnJoinSessionComplete_77D215C44210C770FBA086B82A2056BC Parms{};

	Parms.SessionName = SessionName;
	Parms.Result = Result;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ReciveInvite.WBP_ReciveInvite_C.OnReturn
// (Event, Public, BlueprintEvent)

void UWBP_ReciveInvite_C::OnReturn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReciveInvite_C", "OnReturn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_ReciveInvite.WBP_ReciveInvite_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_ReciveInvite_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReciveInvite_C", "PreConstruct");

	Params::WBP_ReciveInvite_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_ReciveInvite.WBP_ReciveInvite_C.SetSessionEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FOnlineSessionSearchResultBP&SearchRezult_0                                         (BlueprintVisible, BlueprintReadOnly, Parm)
// const class FString&                    UserName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_ReciveInvite_C::SetSessionEvent(const struct FOnlineSessionSearchResultBP& SearchRezult_0, const class FString& UserName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_ReciveInvite_C", "SetSessionEvent");

	Params::WBP_ReciveInvite_C_SetSessionEvent Parms{};

	Parms.SearchRezult_0 = std::move(SearchRezult_0);
	Parms.UserName = std::move(UserName);

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
