#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_cLeonSessionSettings_SearchFriend

#include "Basic.hpp"

#include "WBP_cLeonSessionSettings_SearchFriend_classes.hpp"
#include "WBP_cLeonSessionSettings_SearchFriend_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.AddSearchRezult
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<struct FOnlineSessionSearchResultBP>&Array                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_cLeonSessionSettings_SearchFriend_C::AddSearchRezult(const TArray<struct FOnlineSessionSearchResultBP>& Array)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "AddSearchRezult");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_AddSearchRezult Parms{};

	Parms.Array = std::move(Array);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.BndEvt__WBP_cLeonSessionSettings_LongTapButton_SearchPublicSession_K2Node_ComponentBoundEvent_5_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_cLeonSessionSettings_SearchFriend_C::BndEvt__WBP_cLeonSessionSettings_LongTapButton_SearchPublicSession_K2Node_ComponentBoundEvent_5_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "BndEvt__WBP_cLeonSessionSettings_LongTapButton_SearchPublicSession_K2Node_ComponentBoundEvent_5_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.BndEvt__WBP_cLeonSessionSettings_UpdateModState_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_cLeonSessionSettings_SearchFriend_C::BndEvt__WBP_cLeonSessionSettings_UpdateModState_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "BndEvt__WBP_cLeonSessionSettings_UpdateModState_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.BndEvt__WBP_LinkSessionSettings_LongTapButton_CreateSession_K2Node_ComponentBoundEvent_1_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_cLeonSessionSettings_SearchFriend_C::BndEvt__WBP_LinkSessionSettings_LongTapButton_CreateSession_K2Node_ComponentBoundEvent_1_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "BndEvt__WBP_LinkSessionSettings_LongTapButton_CreateSession_K2Node_ComponentBoundEvent_1_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.BndEvt__WBP_LinkSessionSettings_LongTapButton_JoinSession_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_cLeonSessionSettings_SearchFriend_C::BndEvt__WBP_LinkSessionSettings_LongTapButton_JoinSession_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "BndEvt__WBP_LinkSessionSettings_LongTapButton_JoinSession_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_Password_K2Node_ComponentBoundEvent_4_OnTextCommitted__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// ETextCommit                             CommitMethod                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_Password_K2Node_ComponentBoundEvent_4_OnTextCommitted__DelegateSignature(const class FText& Text, ETextCommit CommitMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_Password_K2Node_ComponentBoundEvent_4_OnTextCommitted__DelegateSignature");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_Password_K2Node_ComponentBoundEvent_4_OnTextCommitted__DelegateSignature Parms{};

	Parms.Text = std::move(Text);
	Parms.CommitMethod = CommitMethod;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_SessionName_K2Node_ComponentBoundEvent_3_OnTextCommitted__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// ETextCommit                             CommitMethod                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_SessionName_K2Node_ComponentBoundEvent_3_OnTextCommitted__DelegateSignature(const class FText& Text, ETextCommit CommitMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_SessionName_K2Node_ComponentBoundEvent_3_OnTextCommitted__DelegateSignature");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_SessionName_K2Node_ComponentBoundEvent_3_OnTextCommitted__DelegateSignature Parms{};

	Parms.Text = std::move(Text);
	Parms.CommitMethod = CommitMethod;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_UserName_K2Node_ComponentBoundEvent_2_OnTextCommitted__DelegateSignature
// (BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// ETextCommit                             CommitMethod                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_UserName_K2Node_ComponentBoundEvent_2_OnTextCommitted__DelegateSignature(const class FText& Text, ETextCommit CommitMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_UserName_K2Node_ComponentBoundEvent_2_OnTextCommitted__DelegateSignature");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_BndEvt__WBP_LinkSessionSettings_WBP_NavInputTextBlock_UserName_K2Node_ComponentBoundEvent_2_OnTextCommitted__DelegateSignature Parms{};

	Parms.Text = std::move(Text);
	Parms.CommitMethod = CommitMethod;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_cLeonSessionSettings_SearchFriend_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.ExecuteUbergraph_WBP_cLeonSessionSettings_SearchFriend
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::ExecuteUbergraph_WBP_cLeonSessionSettings_SearchFriend(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "ExecuteUbergraph_WBP_cLeonSessionSettings_SearchFriend");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_ExecuteUbergraph_WBP_cLeonSessionSettings_SearchFriend Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.Finish
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Rezult                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::Finish(bool Rezult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "Finish");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_Finish Parms{};

	Parms.Rezult = Rezult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.GetRegionName
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FString*                          ReturnString                                           (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::GetRegionName(class FString* ReturnString)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "GetRegionName");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_GetRegionName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ReturnString != nullptr)
		*ReturnString = std::move(Parms.ReturnString);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.GetSearchOption
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FST_SessionOptionString>* Options                                                (Parm, OutParm)

void UWBP_cLeonSessionSettings_SearchFriend_C::GetSearchOption(TArray<struct FST_SessionOptionString>* Options)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "GetSearchOption");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_GetSearchOption Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Options != nullptr)
		*Options = std::move(Parms.Options);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.GetSearchParamaters
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TMap<class FName, struct FSessionSearchParamBP>*Map                                                    (Parm, OutParm)

void UWBP_cLeonSessionSettings_SearchFriend_C::GetSearchParamaters(TMap<class FName, struct FSessionSearchParamBP>* Map)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "GetSearchParamaters");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_GetSearchParamaters Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Map != nullptr)
		*Map = std::move(Parms.Map);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.GetSessionSettings
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FOnlineSessionSettingsBP*        OnlineSessionSettingsBP                                (Parm, OutParm)

void UWBP_cLeonSessionSettings_SearchFriend_C::GetSessionSettings(struct FOnlineSessionSettingsBP* OnlineSessionSettingsBP)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "GetSessionSettings");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_GetSessionSettings Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OnlineSessionSettingsBP != nullptr)
		*OnlineSessionSettingsBP = std::move(Parms.OnlineSessionSettingsBP);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.GetTagNames
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class FName>*                    ReturnTagNames                                         (Parm, OutParm)
// class FString*                          ReturnString                                           (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::GetTagNames(TArray<class FName>* ReturnTagNames, class FString* ReturnString)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "GetTagNames");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_GetTagNames Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ReturnTagNames != nullptr)
		*ReturnTagNames = std::move(Parms.ReturnTagNames);

	if (ReturnString != nullptr)
		*ReturnString = std::move(Parms.ReturnString);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.JoinSession
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FOnlineSessionSearchResultBP&SearchRezult                                           (BlueprintVisible, BlueprintReadOnly, Parm)
// class UWBP_SearchRezult_C*              SelfObject                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::JoinSession(const struct FOnlineSessionSearchResultBP& SearchRezult, class UWBP_SearchRezult_C* SelfObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "JoinSession");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_JoinSession Parms{};

	Parms.SearchRezult = std::move(SearchRezult);
	Parms.SelfObject = SelfObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnActivateEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_TagContent_C*                MyWidget                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnActivateEvent(class UWBP_TagContent_C* MyWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnActivateEvent");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnActivateEvent Parms{};

	Parms.MyWidget = MyWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnCallFailed_0646E9BD4A18BBF176FCAEA4679B2823
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnCallFailed_0646E9BD4A18BBF176FCAEA4679B2823(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnCallFailed_0646E9BD4A18BBF176FCAEA4679B2823");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnCallFailed_0646E9BD4A18BBF176FCAEA4679B2823 Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnCallFailed_0646E9BD4A18BBF176FCAEA471B87116
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnCallFailed_0646E9BD4A18BBF176FCAEA471B87116(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnCallFailed_0646E9BD4A18BBF176FCAEA471B87116");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnCallFailed_0646E9BD4A18BBF176FCAEA471B87116 Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnCallFailed_106CF0804F9221E605B743AFA72FE0AD
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   LocalUserNum                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FString&                    ListName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    ErrorStr                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnCallFailed_106CF0804F9221E605B743AFA72FE0AD(int32 LocalUserNum, bool bWasSuccessful, const class FString& ListName, const class FString& ErrorStr)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnCallFailed_106CF0804F9221E605B743AFA72FE0AD");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnCallFailed_106CF0804F9221E605B743AFA72FE0AD Parms{};

	Parms.LocalUserNum = LocalUserNum;
	Parms.bWasSuccessful = bWasSuccessful;
	Parms.ListName = std::move(ListName);
	Parms.ErrorStr = std::move(ErrorStr);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnCallFailed_1C7907C84B9BCBDA7B50F2A0726445FE
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnCallFailed_1C7907C84B9BCBDA7B50F2A0726445FE(bool bWasSuccessful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnCallFailed_1C7907C84B9BCBDA7B50F2A0726445FE");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnCallFailed_1C7907C84B9BCBDA7B50F2A0726445FE Parms{};

	Parms.bWasSuccessful = bWasSuccessful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnCallFailed_4B844CC6422A1345475C3A95B8ECC827
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             SessionName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EOnJoinSessionCompleteResult_           Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnCallFailed_4B844CC6422A1345475C3A95B8ECC827(class FName SessionName, EOnJoinSessionCompleteResult_ Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnCallFailed_4B844CC6422A1345475C3A95B8ECC827");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnCallFailed_4B844CC6422A1345475C3A95B8ECC827 Parms{};

	Parms.SessionName = SessionName;
	Parms.Result = Result;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnCallFailed_8A1D5F764C11C685F26BD1A63D3E5E8B
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const TArray<struct FOnlineSessionSearchResultBP>&FriendSearchResult                                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnCallFailed_8A1D5F764C11C685F26BD1A63D3E5E8B(bool bWasSuccessful, const TArray<struct FOnlineSessionSearchResultBP>& FriendSearchResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnCallFailed_8A1D5F764C11C685F26BD1A63D3E5E8B");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnCallFailed_8A1D5F764C11C685F26BD1A63D3E5E8B Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.FriendSearchResult = std::move(FriendSearchResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnCallFailed_E9F053F2420C2570B0143C9BC7A331D8
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             SessionName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnCallFailed_E9F053F2420C2570B0143C9BC7A331D8(class FName SessionName, bool bWasSuccessful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnCallFailed_E9F053F2420C2570B0143C9BC7A331D8");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnCallFailed_E9F053F2420C2570B0143C9BC7A331D8 Parms{};

	Parms.SessionName = SessionName;
	Parms.bWasSuccessful = bWasSuccessful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnCreateSessionComplete_E9F053F2420C2570B0143C9BC7A331D8
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             SessionName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnCreateSessionComplete_E9F053F2420C2570B0143C9BC7A331D8(class FName SessionName, bool bWasSuccessful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnCreateSessionComplete_E9F053F2420C2570B0143C9BC7A331D8");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnCreateSessionComplete_E9F053F2420C2570B0143C9BC7A331D8 Parms{};

	Parms.SessionName = SessionName;
	Parms.bWasSuccessful = bWasSuccessful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnFindFriendSessionComplete_8A1D5F764C11C685F26BD1A63D3E5E8B
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const TArray<struct FOnlineSessionSearchResultBP>&FriendSearchResult                                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnFindFriendSessionComplete_8A1D5F764C11C685F26BD1A63D3E5E8B(bool bWasSuccessful, const TArray<struct FOnlineSessionSearchResultBP>& FriendSearchResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnFindFriendSessionComplete_8A1D5F764C11C685F26BD1A63D3E5E8B");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnFindFriendSessionComplete_8A1D5F764C11C685F26BD1A63D3E5E8B Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.FriendSearchResult = std::move(FriendSearchResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnFindSessionsComplete_1C7907C84B9BCBDA7B50F2A0726445FE
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnFindSessionsComplete_1C7907C84B9BCBDA7B50F2A0726445FE(bool bWasSuccessful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnFindSessionsComplete_1C7907C84B9BCBDA7B50F2A0726445FE");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnFindSessionsComplete_1C7907C84B9BCBDA7B50F2A0726445FE Parms{};

	Parms.bWasSuccessful = bWasSuccessful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnFocusLost
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnFocusLost(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnFocusLost");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnFocusLost Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnJoinSessionComplete_4B844CC6422A1345475C3A95B8ECC827
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             SessionName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EOnJoinSessionCompleteResult_           Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnJoinSessionComplete_4B844CC6422A1345475C3A95B8ECC827(class FName SessionName, EOnJoinSessionCompleteResult_ Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnJoinSessionComplete_4B844CC6422A1345475C3A95B8ECC827");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnJoinSessionComplete_4B844CC6422A1345475C3A95B8ECC827 Parms{};

	Parms.SessionName = SessionName;
	Parms.Result = Result;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnReadFriendsListComplete_106CF0804F9221E605B743AFA72FE0AD
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   LocalUserNum                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FString&                    ListName                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// const class FString&                    ErrorStr                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnReadFriendsListComplete_106CF0804F9221E605B743AFA72FE0AD(int32 LocalUserNum, bool bWasSuccessful, const class FString& ListName, const class FString& ErrorStr)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnReadFriendsListComplete_106CF0804F9221E605B743AFA72FE0AD");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnReadFriendsListComplete_106CF0804F9221E605B743AFA72FE0AD Parms{};

	Parms.LocalUserNum = LocalUserNum;
	Parms.bWasSuccessful = bWasSuccessful;
	Parms.ListName = std::move(ListName);
	Parms.ErrorStr = std::move(ErrorStr);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnReturn
// (Event, Public, BlueprintEvent)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnReturn()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnReturn");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA4679B2823
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA4679B2823(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA4679B2823");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA4679B2823 Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA471B87116
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA471B87116(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA471B87116");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnWriteUserFileCanceled_0646E9BD4A18BBF176FCAEA471B87116 Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA4679B2823
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA4679B2823(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA4679B2823");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA4679B2823 Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA471B87116
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA471B87116(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA471B87116");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnWriteUserFileComplete_0646E9BD4A18BBF176FCAEA471B87116 Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA4679B2823
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA4679B2823(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA4679B2823");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA4679B2823 Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA471B87116
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FUniqueNetIdRepl&          UserId                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const class FString&                    Filename                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int64                                   BytesWritten                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA471B87116(bool bWasSuccessful, const struct FUniqueNetIdRepl& UserId, const class FString& Filename, int64 BytesWritten)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA471B87116");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_OnWriteUserFileProgress64_0646E9BD4A18BBF176FCAEA471B87116 Parms{};

	Parms.bWasSuccessful = bWasSuccessful;
	Parms.UserId = std::move(UserId);
	Parms.Filename = std::move(Filename);
	Parms.BytesWritten = BytesWritten;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "PreConstruct");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.SelectMod
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    ModId                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class UWBP_CustomMapParts_C*            SelfWidget                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::SelectMod(const class FString& ModId, class UWBP_CustomMapParts_C* SelfWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "SelectMod");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_SelectMod Parms{};

	Parms.ModId = std::move(ModId);
	Parms.SelfWidget = SelfWidget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_cLeonSessionSettings_SearchFriend_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "Tick");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.UpdateSearch
// (BlueprintCallable, BlueprintEvent)

void UWBP_cLeonSessionSettings_SearchFriend_C::UpdateSearch()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "UpdateSearch");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_cLeonSessionSettings_SearchFriend.WBP_cLeonSessionSettings_SearchFriend_C.WarningControl
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<int32>&                          WarningIndex                                           (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_cLeonSessionSettings_SearchFriend_C::WarningControl(TArray<int32>& WarningIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_cLeonSessionSettings_SearchFriend_C", "WarningControl");

	Params::WBP_cLeonSessionSettings_SearchFriend_C_WarningControl Parms{};

	Parms.WarningIndex = std::move(WarningIndex);

	UObject::ProcessEvent(Func, &Parms);

	WarningIndex = std::move(Parms.WarningIndex);
}


SDK_NAMESPACE_END
