#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PrivateOrPublic

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UINavigation_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_PrivateOrPublic.WBP_PrivateOrPublic_C
// 0x0038 (0x0528 - 0x04F0)
class UWBP_PrivateOrPublic_C final : public UUINavWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWBP_KeyImage_C*                        WBP_KeyImage_2;                                    // 0x04F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_CompressTextBlock_C*               WBP_CompressTextBlock_4;                           // 0x0500(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULongTapButton_OnAnimation_C*           LongTapButton_SearchPublicServer;                  // 0x0508(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULongTapButton_OnAnimation_C*           LongTapButton_SearchPrivateServer;                 // 0x0510(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class ULongTapButton_OnAnimation_C*           LongTapButton_SearchFriendServer;                  // 0x0518(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetAnimation*                       ButtonAnim;                                        // 0x0520(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void BndEvt__WBP_PrivateOrPublic_LongTapButton_SearchFriendServer_K2Node_ComponentBoundEvent_2_PushEnd__DelegateSignature();
	void BndEvt__WBP_PrivateOrPublic_LongTapButton_SearchPrivateServer_K2Node_ComponentBoundEvent_0_PushEnd__DelegateSignature();
	void BndEvt__WBP_PrivateOrPublic_LongTapButton_SearchPublicServer_K2Node_ComponentBoundEvent_1_PushEnd__DelegateSignature();
	void Construct();
	void ExecuteUbergraph_WBP_PrivateOrPublic(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_PrivateOrPublic_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_PrivateOrPublic_C")
	}
	static class UWBP_PrivateOrPublic_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_PrivateOrPublic_C>();
	}
};
// DUMPER7_ASSERTS_UWBP_PrivateOrPublic_C;

SDK_NAMESPACE_END
