#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Home

#include "Basic.hpp"

#include "WBP_Home_classes.hpp"
#include "WBP_Home_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_Button_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_DiscordButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_DiscordButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_DiscordButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LemorionButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LemorionButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LemorionButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LongTapButton_AR_K2Node_ComponentBoundEvent_18_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LongTapButton_AR_K2Node_ComponentBoundEvent_18_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LongTapButton_AR_K2Node_ComponentBoundEvent_18_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LongTapButton_Continue_K2Node_ComponentBoundEvent_9_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LongTapButton_Continue_K2Node_ComponentBoundEvent_9_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LongTapButton_Continue_K2Node_ComponentBoundEvent_9_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LongTapButton_DE_K2Node_ComponentBoundEvent_20_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LongTapButton_DE_K2Node_ComponentBoundEvent_20_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LongTapButton_DE_K2Node_ComponentBoundEvent_20_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LongTapButton_English_K2Node_ComponentBoundEvent_4_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LongTapButton_English_K2Node_ComponentBoundEvent_4_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LongTapButton_English_K2Node_ComponentBoundEvent_4_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LongTapButton_ES_K2Node_ComponentBoundEvent_12_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LongTapButton_ES_K2Node_ComponentBoundEvent_12_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LongTapButton_ES_K2Node_ComponentBoundEvent_12_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LongTapButton_FR_K2Node_ComponentBoundEvent_13_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LongTapButton_FR_K2Node_ComponentBoundEvent_13_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LongTapButton_FR_K2Node_ComponentBoundEvent_13_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LongTapButton_GameEnd_K2Node_ComponentBoundEvent_3_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LongTapButton_GameEnd_K2Node_ComponentBoundEvent_3_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LongTapButton_GameEnd_K2Node_ComponentBoundEvent_3_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LongTapButton_IT_K2Node_ComponentBoundEvent_19_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LongTapButton_IT_K2Node_ComponentBoundEvent_19_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LongTapButton_IT_K2Node_ComponentBoundEvent_19_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LongTapButton_Japanease_K2Node_ComponentBoundEvent_5_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LongTapButton_Japanease_K2Node_ComponentBoundEvent_5_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LongTapButton_Japanease_K2Node_ComponentBoundEvent_5_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LongTapButton_KO_K2Node_ComponentBoundEvent_14_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LongTapButton_KO_K2Node_ComponentBoundEvent_14_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LongTapButton_KO_K2Node_ComponentBoundEvent_14_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LongTapButton_PT_K2Node_ComponentBoundEvent_11_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LongTapButton_PT_K2Node_ComponentBoundEvent_11_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LongTapButton_PT_K2Node_ComponentBoundEvent_11_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LongTapButton_RU_K2Node_ComponentBoundEvent_21_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LongTapButton_RU_K2Node_ComponentBoundEvent_21_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LongTapButton_RU_K2Node_ComponentBoundEvent_21_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LongTapButton_SC_K2Node_ComponentBoundEvent_6_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LongTapButton_SC_K2Node_ComponentBoundEvent_6_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LongTapButton_SC_K2Node_ComponentBoundEvent_6_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LongTapButton_SearchSurver_K2Node_ComponentBoundEvent_22_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LongTapButton_SearchSurver_K2Node_ComponentBoundEvent_22_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LongTapButton_SearchSurver_K2Node_ComponentBoundEvent_22_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LongTapButton_SessionSettings_K2Node_ComponentBoundEvent_16_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LongTapButton_SessionSettings_K2Node_ComponentBoundEvent_16_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LongTapButton_SessionSettings_K2Node_ComponentBoundEvent_16_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LongTapButton_Setting_K2Node_ComponentBoundEvent_10_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LongTapButton_Setting_K2Node_ComponentBoundEvent_10_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LongTapButton_Setting_K2Node_ComponentBoundEvent_10_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LongTapButton_Start_K2Node_ComponentBoundEvent_8_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LongTapButton_Start_K2Node_ComponentBoundEvent_8_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LongTapButton_Start_K2Node_ComponentBoundEvent_8_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LongTapButton_TC_K2Node_ComponentBoundEvent_7_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LongTapButton_TC_K2Node_ComponentBoundEvent_7_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LongTapButton_TC_K2Node_ComponentBoundEvent_7_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_LongTapButton_Tutorial_K2Node_ComponentBoundEvent_15_PushEnd__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_LongTapButton_Tutorial_K2Node_ComponentBoundEvent_15_PushEnd__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_LongTapButton_Tutorial_K2Node_ComponentBoundEvent_15_PushEnd__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.BndEvt__WBP_Home_UINavButtonBase_132_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_Home_C::BndEvt__WBP_Home_UINavButtonBase_132_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "BndEvt__WBP_Home_UINavButtonBase_132_K2Node_ComponentBoundEvent_17_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Home_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Home.WBP_Home_C.ExecuteUbergraph_WBP_Home
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Home_C::ExecuteUbergraph_WBP_Home(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "ExecuteUbergraph_WBP_Home");

	Params::WBP_Home_C_ExecuteUbergraph_WBP_Home Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Home.WBP_Home_C.GetInitialFocusComponent
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUINavComponent*                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UUINavComponent* UWBP_Home_C::GetInitialFocusComponent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "GetInitialFocusComponent");

	Params::WBP_Home_C_GetInitialFocusComponent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Home.WBP_Home_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Home_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Home_C", "PreConstruct");

	Params::WBP_Home_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
